// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module monte_sim_dev_sqrt_fixed_32_16_s (
        ap_clk,
        ap_rst,
        x_V,
        ap_return,
        ap_ext_blocking_n,
        ap_str_blocking_n,
        ap_int_blocking_n
);


input   ap_clk;
input   ap_rst;
input  [31:0] x_V;
output  [23:0] ap_return;
output   ap_ext_blocking_n;
output   ap_str_blocking_n;
output   ap_int_blocking_n;

reg   [31:0] x_V_read_reg_3682;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_state5_pp0_stage0_iter4;
wire    ap_block_state6_pp0_stage0_iter5;
wire    ap_block_state7_pp0_stage0_iter6;
wire    ap_block_state8_pp0_stage0_iter7;
wire    ap_block_state9_pp0_stage0_iter8;
wire    ap_block_state10_pp0_stage0_iter9;
wire    ap_block_state11_pp0_stage0_iter10;
wire    ap_block_state12_pp0_stage0_iter11;
wire    ap_block_state13_pp0_stage0_iter12;
wire    ap_block_pp0_stage0_11001;
reg   [31:0] x_V_read_reg_3682_pp0_iter1_reg;
reg   [31:0] x_V_read_reg_3682_pp0_iter2_reg;
reg   [31:0] x_V_read_reg_3682_pp0_iter3_reg;
reg   [31:0] x_V_read_reg_3682_pp0_iter4_reg;
reg   [31:0] x_V_read_reg_3682_pp0_iter5_reg;
reg   [31:0] x_V_read_reg_3682_pp0_iter6_reg;
reg   [31:0] x_V_read_reg_3682_pp0_iter7_reg;
reg   [31:0] x_V_read_reg_3682_pp0_iter8_reg;
reg   [31:0] x_V_read_reg_3682_pp0_iter9_reg;
reg   [31:0] x_V_read_reg_3682_pp0_iter10_reg;
reg   [31:0] x_V_read_reg_3682_pp0_iter11_reg;
wire   [15:0] trunc_ln731_fu_302_p1;
reg   [15:0] trunc_ln731_reg_3687;
reg   [15:0] trunc_ln731_reg_3687_pp0_iter1_reg;
reg   [15:0] trunc_ln731_reg_3687_pp0_iter2_reg;
wire   [7:0] select_ln488_2_fu_426_p3;
reg   [7:0] select_ln488_2_reg_3692;
wire   [18:0] select_ln488_3_fu_434_p3;
reg   [18:0] select_ln488_3_reg_3698;
wire   [0:0] icmp_ln488_2_fu_474_p2;
reg   [0:0] icmp_ln488_2_reg_3704;
wire   [4:0] sub_ln248_1_fu_480_p2;
reg   [4:0] sub_ln248_1_reg_3710;
wire   [0:0] icmp_ln1495_fu_496_p2;
reg   [0:0] icmp_ln1495_reg_3715;
reg   [0:0] icmp_ln1495_reg_3715_pp0_iter1_reg;
reg   [0:0] icmp_ln1495_reg_3715_pp0_iter2_reg;
wire   [0:0] icmp_ln318_fu_512_p2;
reg   [0:0] icmp_ln318_reg_3720;
reg   [0:0] icmp_ln318_reg_3720_pp0_iter1_reg;
reg   [0:0] icmp_ln318_reg_3720_pp0_iter2_reg;
wire   [7:0] select_ln488_8_fu_697_p3;
reg   [7:0] select_ln488_8_reg_3725;
wire   [18:0] select_ln488_9_fu_705_p3;
reg   [18:0] select_ln488_9_reg_3731;
wire   [0:0] icmp_ln488_5_fu_745_p2;
reg   [0:0] icmp_ln488_5_reg_3737;
wire   [7:0] sub_ln248_4_fu_751_p2;
reg   [7:0] sub_ln248_4_reg_3743;
wire   [7:0] select_ln488_12_fu_854_p3;
reg   [7:0] select_ln488_12_reg_3748;
wire   [0:0] icmp_ln488_7_fu_886_p2;
reg   [0:0] icmp_ln488_7_reg_3754;
wire   [18:0] select_ln488_15_fu_910_p3;
reg   [18:0] select_ln488_15_reg_3759;
wire   [7:0] select_ln488_14_fu_934_p3;
reg   [7:0] select_ln488_14_reg_3768;
reg   [7:0] select_ln488_14_reg_3768_pp0_iter4_reg;
reg   [7:0] select_ln488_14_reg_3768_pp0_iter5_reg;
reg   [7:0] select_ln488_14_reg_3768_pp0_iter6_reg;
reg   [7:0] select_ln488_14_reg_3768_pp0_iter7_reg;
reg   [7:0] select_ln488_14_reg_3768_pp0_iter8_reg;
reg   [7:0] select_ln488_14_reg_3768_pp0_iter9_reg;
reg   [7:0] select_ln488_14_reg_3768_pp0_iter10_reg;
reg   [7:0] select_ln488_14_reg_3768_pp0_iter11_reg;
wire   [18:0] select_ln318_2_fu_1012_p3;
reg   [18:0] select_ln318_2_reg_3783;
wire   [18:0] sub_ln703_2_fu_1103_p2;
reg   [18:0] sub_ln703_2_reg_3788;
wire   [0:0] or_ln318_1_fu_1137_p2;
reg   [0:0] or_ln318_1_reg_3793;
wire   [16:0] select_ln318_3_fu_1143_p3;
reg   [16:0] select_ln318_3_reg_3798;
wire   [16:0] select_ln318_4_fu_1151_p3;
reg   [16:0] select_ln318_4_reg_3804;
reg   [2:0] p_Result_34_2_reg_3812;
reg   [5:0] tmp_15_reg_3817;
wire   [1:0] trunc_ln708_24_fu_1179_p1;
reg   [1:0] trunc_ln708_24_reg_3822;
reg   [4:0] tmp_17_reg_3827;
wire   [2:0] trunc_ln708_25_fu_1193_p1;
reg   [2:0] trunc_ln708_25_reg_3832;
reg   [3:0] tmp_19_reg_3837;
reg   [3:0] tmp_19_reg_3837_pp0_iter4_reg;
wire   [3:0] trunc_ln708_26_fu_1207_p1;
reg   [3:0] trunc_ln708_26_reg_3842;
reg   [3:0] trunc_ln708_26_reg_3842_pp0_iter4_reg;
reg   [2:0] tmp_21_reg_3847;
reg   [2:0] tmp_21_reg_3847_pp0_iter4_reg;
wire   [4:0] trunc_ln708_27_fu_1221_p1;
reg   [4:0] trunc_ln708_27_reg_3852;
reg   [4:0] trunc_ln708_27_reg_3852_pp0_iter4_reg;
reg   [1:0] tmp_23_reg_3857;
reg   [1:0] tmp_23_reg_3857_pp0_iter4_reg;
reg   [1:0] tmp_23_reg_3857_pp0_iter5_reg;
wire   [5:0] trunc_ln708_28_fu_1235_p1;
reg   [5:0] trunc_ln708_28_reg_3862;
reg   [5:0] trunc_ln708_28_reg_3862_pp0_iter4_reg;
reg   [5:0] trunc_ln708_28_reg_3862_pp0_iter5_reg;
reg   [0:0] tmp_44_reg_3867;
reg   [0:0] tmp_44_reg_3867_pp0_iter4_reg;
reg   [0:0] tmp_44_reg_3867_pp0_iter5_reg;
wire   [6:0] trunc_ln708_29_fu_1247_p1;
reg   [6:0] trunc_ln708_29_reg_3872;
reg   [6:0] trunc_ln708_29_reg_3872_pp0_iter4_reg;
reg   [6:0] trunc_ln708_29_reg_3872_pp0_iter5_reg;
wire   [18:0] select_ln318_8_fu_1363_p3;
reg   [18:0] select_ln318_8_reg_3877;
wire   [18:0] sub_ln703_6_fu_1439_p2;
reg   [18:0] sub_ln703_6_reg_3882;
wire   [0:0] or_ln318_3_fu_1473_p2;
reg   [0:0] or_ln318_3_reg_3887;
wire   [16:0] select_ln318_9_fu_1479_p3;
reg   [16:0] select_ln318_9_reg_3892;
wire   [16:0] select_ln318_10_fu_1487_p3;
reg   [16:0] select_ln318_10_reg_3898;
reg   [4:0] p_Result_34_4_reg_3906;
wire   [18:0] select_ln318_14_fu_1617_p3;
reg   [18:0] select_ln318_14_reg_3911;
wire   [18:0] sub_ln703_10_fu_1693_p2;
reg   [18:0] sub_ln703_10_reg_3916;
wire   [0:0] or_ln318_5_fu_1727_p2;
reg   [0:0] or_ln318_5_reg_3921;
wire   [16:0] select_ln318_15_fu_1733_p3;
reg   [16:0] select_ln318_15_reg_3926;
wire   [16:0] select_ln318_16_fu_1741_p3;
reg   [16:0] select_ln318_16_reg_3932;
reg   [6:0] p_Result_34_6_reg_3940;
wire   [16:0] select_ln318_18_fu_1857_p3;
reg   [16:0] select_ln318_18_reg_3945;
wire   [18:0] select_ln318_20_fu_1871_p3;
reg   [18:0] select_ln318_20_reg_3951;
wire   [18:0] sub_ln703_14_fu_1947_p2;
reg   [18:0] sub_ln703_14_reg_3956;
wire   [0:0] or_ln318_7_fu_1971_p2;
reg   [0:0] or_ln318_7_reg_3961;
wire   [16:0] select_ln318_22_fu_1977_p3;
reg   [16:0] select_ln318_22_reg_3967;
wire   [16:0] select_ln318_24_fu_2097_p3;
reg   [16:0] select_ln318_24_reg_3975;
wire   [16:0] select_ln318_26_fu_2113_p3;
reg   [16:0] select_ln318_26_reg_3981;
wire   [18:0] select_ln318_27_fu_2120_p3;
reg   [18:0] select_ln318_27_reg_3989;
wire   [16:0] trunc_ln708_16_fu_2148_p4;
reg   [16:0] trunc_ln708_16_reg_3996;
wire   [0:0] icmp_ln1496_fu_2195_p2;
reg   [0:0] icmp_ln1496_reg_4003;
wire   [0:0] or_ln318_12_fu_2231_p2;
reg   [0:0] or_ln318_12_reg_4009;
wire   [16:0] select_ln318_29_fu_2237_p3;
reg   [16:0] select_ln318_29_reg_4016;
wire   [16:0] select_ln318_28_fu_2302_p3;
reg   [16:0] select_ln318_28_reg_4023;
wire   [0:0] or_ln318_16_fu_2479_p2;
reg   [0:0] or_ln318_16_reg_4029;
wire   [16:0] select_ln318_33_fu_2485_p3;
reg   [16:0] select_ln318_33_reg_4034;
wire   [16:0] select_ln318_34_fu_2492_p3;
reg   [16:0] select_ln318_34_reg_4041;
wire   [18:0] select_ln318_35_fu_2500_p3;
reg   [18:0] select_ln318_35_reg_4051;
wire   [16:0] select_ln318_36_fu_2689_p3;
reg   [16:0] select_ln318_36_reg_4060;
wire   [16:0] select_ln318_37_fu_2697_p3;
reg   [16:0] select_ln318_37_reg_4066;
wire   [16:0] select_ln318_38_fu_2704_p3;
reg   [16:0] select_ln318_38_reg_4072;
wire   [18:0] select_ln318_39_fu_2711_p3;
reg   [18:0] select_ln318_39_reg_4080;
wire   [16:0] trunc_ln708_19_fu_2738_p4;
reg   [16:0] trunc_ln708_19_reg_4087;
wire   [16:0] mul_FL_V_2_fu_2747_p3;
reg   [16:0] mul_FL_V_2_reg_4094;
wire   [0:0] icmp_ln1494_12_fu_2755_p2;
reg   [0:0] icmp_ln1494_12_reg_4099;
wire   [0:0] icmp_ln1498_12_fu_2761_p2;
reg   [0:0] icmp_ln1498_12_reg_4105;
wire   [0:0] icmp_ln1494_21_fu_2767_p2;
reg   [0:0] icmp_ln1494_21_reg_4110;
wire   [0:0] icmp_ln318_11_fu_2773_p2;
reg   [0:0] icmp_ln318_11_reg_4115;
wire   [0:0] icmp_ln1496_3_fu_2779_p2;
reg   [0:0] icmp_ln1496_3_reg_4120;
wire   [16:0] select_ln318_44_fu_3081_p3;
reg   [16:0] select_ln318_44_reg_4127;
wire   [16:0] select_ln318_45_fu_3089_p3;
reg   [16:0] select_ln318_45_reg_4133;
wire   [16:0] select_ln318_46_fu_3097_p3;
reg   [16:0] select_ln318_46_reg_4140;
wire   [18:0] select_ln318_47_fu_3105_p3;
reg   [18:0] select_ln318_47_reg_4150;
reg   [11:0] tmp_12_reg_4159;
reg   [2:0] tmp_33_reg_4164;
wire   [16:0] select_ln318_48_fu_3276_p3;
reg   [16:0] select_ln318_48_reg_4169;
wire   [16:0] select_ln318_49_fu_3283_p3;
reg   [16:0] select_ln318_49_reg_4175;
wire   [16:0] select_ln318_50_fu_3290_p3;
reg   [16:0] select_ln318_50_reg_4181;
wire   [18:0] select_ln318_51_fu_3297_p3;
reg   [18:0] select_ln318_51_reg_4186;
wire   [16:0] mul_FL_V_5_fu_3333_p3;
reg   [16:0] mul_FL_V_5_reg_4191;
wire   [16:0] add_ln703_22_fu_3427_p2;
reg   [16:0] add_ln703_22_reg_4196;
wire   [18:0] select_ln339_15_fu_3439_p3;
reg   [18:0] select_ln339_15_reg_4201;
wire   [0:0] or_ln318_37_fu_3459_p2;
reg   [0:0] or_ln318_37_reg_4206;
wire    ap_block_pp0_stage0;
wire   [15:0] trunc_ln_fu_288_p4;
wire   [1:0] tmp_fu_306_p4;
wire   [2:0] zext_ln248_fu_316_p1;
wire   [18:0] x_l_I_V_fu_298_p1;
wire   [2:0] add_ln248_fu_326_p2;
wire   [0:0] icmp_ln488_fu_320_p2;
wire   [18:0] p_Result_s_77_fu_332_p5;
wire   [7:0] select_ln488_fu_344_p3;
wire   [1:0] p_Result_25_1_fu_360_p4;
wire   [18:0] select_ln488_1_fu_352_p3;
wire   [2:0] tmp_1_fu_370_p3;
wire   [3:0] p_Result_28_1_fu_378_p4;
wire   [3:0] zext_ln488_fu_388_p1;
wire   [3:0] sub_ln248_fu_398_p2;
wire   [0:0] icmp_ln488_1_fu_392_p2;
reg   [7:0] tmp_16_fu_416_p4;
wire   [18:0] p_Result_30_1_fu_404_p5;
wire   [2:0] p_Result_25_2_fu_442_p4;
wire   [3:0] tmp_2_fu_452_p3;
wire   [4:0] p_Result_28_2_fu_460_p4;
wire   [4:0] zext_ln488_1_fu_470_p1;
wire   [1:0] tmp_28_fu_486_p4;
wire   [1:0] tmp_36_fu_502_p4;
reg   [7:0] tmp_18_fu_528_p4;
wire   [18:0] p_Result_30_2_fu_518_p5;
wire   [7:0] select_ln488_4_fu_537_p3;
wire   [3:0] p_Result_25_3_fu_549_p4;
wire   [18:0] select_ln488_5_fu_543_p3;
wire   [4:0] tmp_3_fu_559_p3;
wire   [5:0] p_Result_28_3_fu_567_p4;
wire   [5:0] zext_ln488_2_fu_577_p1;
wire   [5:0] sub_ln248_2_fu_587_p2;
wire   [0:0] icmp_ln488_3_fu_581_p2;
reg   [7:0] tmp_20_fu_605_p4;
wire   [18:0] p_Result_30_3_fu_593_p5;
wire   [7:0] select_ln488_6_fu_615_p3;
wire   [4:0] p_Result_25_4_fu_631_p4;
wire   [18:0] select_ln488_7_fu_623_p3;
wire   [5:0] tmp_4_fu_641_p3;
wire   [6:0] p_Result_28_4_fu_649_p4;
wire   [6:0] zext_ln488_3_fu_659_p1;
wire   [6:0] sub_ln248_3_fu_669_p2;
wire   [0:0] icmp_ln488_4_fu_663_p2;
reg   [7:0] tmp_22_fu_687_p4;
wire   [18:0] p_Result_30_4_fu_675_p5;
wire   [5:0] p_Result_25_5_fu_713_p4;
wire   [6:0] tmp_5_fu_723_p3;
wire   [7:0] p_Result_28_5_fu_731_p4;
wire   [7:0] zext_ln488_4_fu_741_p1;
reg   [7:0] tmp_24_fu_767_p4;
wire   [18:0] p_Result_30_5_fu_757_p5;
wire   [7:0] select_ln488_10_fu_776_p3;
wire   [6:0] p_Result_25_6_fu_788_p4;
wire   [18:0] select_ln488_11_fu_782_p3;
wire   [7:0] tmp_6_fu_798_p3;
wire   [8:0] p_Result_28_6_fu_806_p4;
wire   [8:0] zext_ln488_5_fu_816_p1;
wire   [8:0] sub_ln248_5_fu_826_p2;
wire   [0:0] icmp_ln488_6_fu_820_p2;
reg   [7:0] tmp_26_fu_844_p4;
wire   [18:0] p_Result_30_6_fu_832_p5;
wire   [18:0] select_ln488_13_fu_862_p3;
wire   [8:0] tmp_7_fu_870_p3;
wire   [9:0] trunc_ln612_fu_878_p1;
wire   [9:0] zext_ln488_6_fu_882_p1;
wire   [9:0] sub_ln248_6_fu_892_p2;
wire   [18:0] p_Result_30_7_fu_898_p5;
reg   [7:0] tmp_27_fu_925_p4;
wire   [16:0] trunc_ln708_1_fu_940_p3;
wire   [18:0] zext_ln1494_fu_948_p1;
wire   [16:0] x_l_FH_V_fu_918_p3;
wire   [18:0] add_ln703_fu_968_p2;
wire   [18:0] select_ln339_fu_973_p3;
wire   [0:0] icmp_ln1498_fu_957_p2;
wire   [0:0] and_ln318_fu_985_p2;
wire   [0:0] icmp_ln1494_fu_952_p2;
wire   [0:0] or_ln318_fu_990_p2;
wire   [16:0] add_ln703_24_fu_962_p2;
wire   [18:0] sub_ln703_fu_979_p2;
wire   [16:0] select_ln318_fu_996_p3;
wire   [6:0] tmp_14_fu_1029_p4;
wire   [0:0] trunc_ln708_fu_1047_p1;
wire   [1:0] p_Result_34_1_fu_1019_p4;
wire   [16:0] trunc_ln708_3_fu_1039_p3;
wire   [18:0] zext_ln1494_1_fu_1061_p1;
wire   [16:0] select_ln318_1_fu_1004_p3;
wire   [16:0] trunc_ln708_4_fu_1051_p4;
wire   [0:0] icmp_ln1495_1_fu_1077_p2;
wire   [18:0] add_ln703_1_fu_1089_p2;
wire   [18:0] select_ln339_1_fu_1095_p3;
wire   [0:0] icmp_ln318_1_fu_1119_p2;
wire   [0:0] icmp_ln1498_1_fu_1071_p2;
wire   [0:0] xor_ln318_8_fu_1125_p2;
wire   [0:0] and_ln318_1_fu_1131_p2;
wire   [0:0] icmp_ln1494_1_fu_1065_p2;
reg   [16:0] tmp_38_fu_1109_p4;
wire   [16:0] sub_ln703_1_fu_1083_p2;
wire   [16:0] trunc_ln708_5_fu_1256_p3;
wire   [18:0] select_ln318_5_fu_1251_p3;
wire   [18:0] zext_ln1494_2_fu_1271_p1;
wire   [16:0] trunc_ln708_6_fu_1263_p4;
wire   [0:0] icmp_ln1495_2_fu_1287_p2;
wire   [18:0] add_ln703_2_fu_1297_p2;
wire   [18:0] select_ln339_2_fu_1303_p3;
wire   [0:0] icmp_ln318_2_fu_1326_p2;
wire   [0:0] icmp_ln1498_2_fu_1281_p2;
wire   [0:0] xor_ln318_9_fu_1331_p2;
wire   [0:0] and_ln318_2_fu_1337_p2;
wire   [0:0] icmp_ln1494_2_fu_1275_p2;
wire   [0:0] or_ln318_2_fu_1343_p2;
reg   [16:0] tmp_39_fu_1317_p4;
wire   [16:0] sub_ln703_3_fu_1292_p2;
wire   [18:0] sub_ln703_4_fu_1311_p2;
wire   [16:0] select_ln318_6_fu_1349_p3;
wire   [3:0] p_Result_34_3_fu_1371_p4;
wire   [16:0] trunc_ln708_7_fu_1381_p3;
wire   [18:0] zext_ln1494_3_fu_1397_p1;
wire   [16:0] select_ln318_7_fu_1356_p3;
wire   [16:0] trunc_ln708_8_fu_1388_p4;
wire   [0:0] icmp_ln1495_3_fu_1413_p2;
wire   [18:0] add_ln703_3_fu_1425_p2;
wire   [18:0] select_ln339_3_fu_1431_p3;
wire   [0:0] icmp_ln318_3_fu_1455_p2;
wire   [0:0] icmp_ln1498_3_fu_1407_p2;
wire   [0:0] xor_ln318_10_fu_1461_p2;
wire   [0:0] and_ln318_3_fu_1467_p2;
wire   [0:0] icmp_ln1494_3_fu_1401_p2;
reg   [16:0] tmp_40_fu_1445_p4;
wire   [16:0] sub_ln703_5_fu_1419_p2;
wire   [16:0] trunc_ln708_9_fu_1510_p3;
wire   [18:0] select_ln318_11_fu_1505_p3;
wire   [18:0] zext_ln1494_4_fu_1525_p1;
wire   [16:0] trunc_ln708_s_fu_1517_p4;
wire   [0:0] icmp_ln1495_4_fu_1541_p2;
wire   [18:0] add_ln703_4_fu_1551_p2;
wire   [18:0] select_ln339_4_fu_1557_p3;
wire   [0:0] icmp_ln318_4_fu_1580_p2;
wire   [0:0] icmp_ln1498_4_fu_1535_p2;
wire   [0:0] xor_ln318_11_fu_1585_p2;
wire   [0:0] and_ln318_4_fu_1591_p2;
wire   [0:0] icmp_ln1494_4_fu_1529_p2;
wire   [0:0] or_ln318_4_fu_1597_p2;
reg   [16:0] tmp_41_fu_1571_p4;
wire   [16:0] sub_ln703_7_fu_1546_p2;
wire   [18:0] sub_ln703_8_fu_1565_p2;
wire   [16:0] select_ln318_12_fu_1603_p3;
wire   [5:0] p_Result_34_5_fu_1625_p4;
wire   [16:0] trunc_ln708_2_fu_1635_p3;
wire   [18:0] zext_ln1494_5_fu_1651_p1;
wire   [16:0] select_ln318_13_fu_1610_p3;
wire   [16:0] trunc_ln708_10_fu_1642_p4;
wire   [0:0] icmp_ln1495_5_fu_1667_p2;
wire   [18:0] add_ln703_5_fu_1679_p2;
wire   [18:0] select_ln339_5_fu_1685_p3;
wire   [0:0] icmp_ln318_5_fu_1709_p2;
wire   [0:0] icmp_ln1498_5_fu_1661_p2;
wire   [0:0] xor_ln318_12_fu_1715_p2;
wire   [0:0] and_ln318_5_fu_1721_p2;
wire   [0:0] icmp_ln1494_5_fu_1655_p2;
reg   [16:0] tmp_42_fu_1699_p4;
wire   [16:0] sub_ln703_9_fu_1673_p2;
wire   [16:0] trunc_ln708_11_fu_1764_p3;
wire   [18:0] select_ln318_17_fu_1759_p3;
wire   [18:0] zext_ln1494_6_fu_1779_p1;
wire   [16:0] trunc_ln708_12_fu_1771_p4;
wire   [0:0] icmp_ln1495_6_fu_1795_p2;
wire   [18:0] add_ln703_6_fu_1805_p2;
wire   [18:0] select_ln339_6_fu_1811_p3;
wire   [0:0] icmp_ln318_6_fu_1834_p2;
wire   [0:0] icmp_ln1498_6_fu_1789_p2;
wire   [0:0] xor_ln318_13_fu_1839_p2;
wire   [0:0] and_ln318_6_fu_1845_p2;
wire   [0:0] icmp_ln1494_6_fu_1783_p2;
wire   [0:0] or_ln318_6_fu_1851_p2;
reg   [16:0] tmp_43_fu_1825_p4;
wire   [16:0] sub_ln703_11_fu_1800_p2;
wire   [18:0] sub_ln703_12_fu_1819_p2;
wire   [7:0] p_Result_34_7_fu_1879_p4;
wire   [16:0] trunc_ln708_13_fu_1889_p3;
wire   [18:0] zext_ln1494_7_fu_1905_p1;
wire   [16:0] select_ln318_19_fu_1864_p3;
wire   [16:0] trunc_ln708_14_fu_1896_p4;
wire   [0:0] icmp_ln1495_7_fu_1921_p2;
wire   [18:0] add_ln703_7_fu_1933_p2;
wire   [18:0] select_ln339_7_fu_1939_p3;
wire   [0:0] icmp_ln318_7_fu_1953_p2;
wire   [0:0] icmp_ln1498_7_fu_1915_p2;
wire   [0:0] xor_ln318_14_fu_1959_p2;
wire   [0:0] and_ln318_7_fu_1965_p2;
wire   [0:0] icmp_ln1494_7_fu_1909_p2;
wire   [16:0] sub_ln703_13_fu_1927_p2;
reg   [16:0] tmp_45_fu_1985_p4;
wire   [16:0] select_ln318_21_fu_1994_p3;
wire   [8:0] p_Result_34_8_fu_2005_p4;
wire   [18:0] select_ln318_23_fu_2000_p3;
wire   [16:0] trunc_ln708_15_fu_2015_p3;
wire   [0:0] icmp_ln1498_8_fu_2028_p2;
wire   [0:0] icmp_ln1494_17_fu_2034_p2;
wire   [0:0] icmp_ln331_fu_2045_p2;
wire   [16:0] xor_ln703_fu_2056_p2;
wire   [0:0] xor_ln331_fu_2050_p2;
wire   [18:0] add_ln703_9_fu_2067_p2;
wire   [0:0] icmp_ln1494_8_fu_2022_p2;
wire   [0:0] and_ln318_8_fu_2039_p2;
wire   [0:0] or_ln318_8_fu_2091_p2;
reg   [16:0] tmp_46_fu_2081_p4;
wire   [16:0] add_ln703_8_fu_2062_p2;
wire   [18:0] select_ln339_8_fu_2073_p3;
wire   [7:0] tmp_25_fu_2138_p4;
wire   [1:0] tmp_8_fu_2128_p4;
wire   [0:0] icmp_ln1498_9_fu_2171_p2;
wire   [0:0] icmp_ln1494_18_fu_2177_p2;
wire   [16:0] select_ln318_25_fu_2105_p3;
wire   [16:0] mul_FL_V_9_fu_2157_p3;
wire   [0:0] icmp_ln1494_9_fu_2165_p2;
wire   [0:0] or_ln318_10_fu_2201_p2;
wire   [0:0] icmp_ln318_8_fu_2189_p2;
wire   [0:0] or_ln318_9_fu_2207_p2;
wire   [0:0] and_ln318_9_fu_2183_p2;
wire   [0:0] xor_ln318_fu_2219_p2;
wire   [0:0] or_ln318_11_fu_2225_p2;
wire   [16:0] sub_ln703_15_fu_2213_p2;
wire   [0:0] icmp_ln1498_17_fu_2249_p2;
wire   [0:0] icmp_ln1495_8_fu_2245_p2;
wire   [0:0] and_ln331_fu_2253_p2;
wire   [16:0] p_neg_9_fu_2264_p3;
wire   [16:0] sub_ln703_16_fu_2271_p2;
wire   [0:0] or_ln331_fu_2258_p2;
wire   [18:0] add_ln703_11_fu_2281_p2;
reg   [16:0] tmp_47_fu_2293_p4;
wire   [16:0] add_ln703_10_fu_2276_p2;
wire   [18:0] select_ln339_9_fu_2286_p3;
wire   [6:0] tmp_29_fu_2330_p4;
wire   [3:0] tmp_9_fu_2320_p4;
wire   [18:0] select_ln318_31_fu_2314_p3;
wire   [16:0] select_ln318_30_fu_2308_p3;
wire   [16:0] trunc_ln708_17_fu_2340_p4;
wire   [0:0] icmp_ln1498_10_fu_2363_p2;
wire   [0:0] icmp_ln1494_19_fu_2369_p2;
wire   [16:0] mul_FL_V_s_fu_2349_p3;
wire   [0:0] icmp_ln1494_10_fu_2357_p2;
wire   [0:0] icmp_ln1496_1_fu_2387_p2;
wire   [0:0] or_ln318_13_fu_2392_p2;
wire   [0:0] icmp_ln318_9_fu_2381_p2;
wire   [0:0] icmp_ln1498_18_fu_2415_p2;
wire   [0:0] icmp_ln1495_9_fu_2409_p2;
wire   [0:0] and_ln331_1_fu_2421_p2;
wire   [16:0] p_neg_10_fu_2433_p3;
wire   [16:0] sub_ln703_18_fu_2441_p2;
wire   [0:0] or_ln331_1_fu_2427_p2;
wire   [18:0] add_ln703_13_fu_2453_p2;
wire   [0:0] or_ln318_14_fu_2398_p2;
wire   [0:0] and_ln318_10_fu_2375_p2;
wire   [0:0] xor_ln318_1_fu_2467_p2;
wire   [0:0] or_ln318_15_fu_2473_p2;
wire   [16:0] sub_ln703_17_fu_2404_p2;
wire   [16:0] add_ln703_12_fu_2447_p2;
wire   [18:0] select_ln339_10_fu_2459_p3;
reg   [16:0] tmp_48_fu_2508_p4;
wire   [16:0] select_ln318_32_fu_2517_p3;
wire   [5:0] tmp_30_fu_2533_p4;
wire   [5:0] tmp_s_fu_2523_p4;
wire   [16:0] trunc_ln708_18_fu_2543_p4;
wire   [0:0] icmp_ln1498_11_fu_2565_p2;
wire   [0:0] icmp_ln1494_20_fu_2570_p2;
wire   [16:0] mul_FL_V_1_fu_2552_p3;
wire   [0:0] icmp_ln1494_11_fu_2560_p2;
wire   [0:0] icmp_ln1496_2_fu_2586_p2;
wire   [0:0] or_ln318_17_fu_2591_p2;
wire   [0:0] icmp_ln318_10_fu_2581_p2;
wire   [0:0] icmp_ln1498_19_fu_2613_p2;
wire   [0:0] icmp_ln1495_10_fu_2608_p2;
wire   [0:0] and_ln331_2_fu_2618_p2;
wire   [16:0] p_neg_11_fu_2630_p3;
wire   [16:0] sub_ln703_20_fu_2638_p2;
wire   [0:0] or_ln331_2_fu_2624_p2;
wire   [18:0] add_ln703_15_fu_2649_p2;
wire   [0:0] or_ln318_18_fu_2597_p2;
wire   [0:0] and_ln318_11_fu_2575_p2;
wire   [0:0] xor_ln318_2_fu_2671_p2;
wire   [0:0] or_ln318_24_fu_2677_p2;
wire   [0:0] or_ln318_25_fu_2683_p2;
reg   [16:0] tmp_49_fu_2661_p4;
wire   [16:0] sub_ln703_19_fu_2603_p2;
wire   [16:0] add_ln703_14_fu_2644_p2;
wire   [18:0] select_ln339_11_fu_2654_p3;
wire   [4:0] tmp_31_fu_2728_p4;
wire   [7:0] tmp_10_fu_2718_p4;
wire   [0:0] or_ln318_26_fu_2789_p2;
wire   [0:0] icmp_ln1498_20_fu_2806_p2;
wire   [0:0] icmp_ln1495_11_fu_2802_p2;
wire   [0:0] and_ln331_3_fu_2810_p2;
wire   [16:0] p_neg_12_fu_2821_p3;
wire   [16:0] sub_ln703_22_fu_2828_p2;
wire   [0:0] or_ln331_3_fu_2815_p2;
wire   [18:0] add_ln703_17_fu_2838_p2;
wire   [0:0] or_ln318_19_fu_2793_p2;
wire   [0:0] and_ln318_12_fu_2785_p2;
wire   [0:0] xor_ln318_3_fu_2859_p2;
wire   [0:0] or_ln318_27_fu_2865_p2;
wire   [0:0] or_ln318_28_fu_2871_p2;
reg   [16:0] tmp_50_fu_2850_p4;
wire   [16:0] sub_ln703_21_fu_2798_p2;
wire   [16:0] add_ln703_16_fu_2833_p2;
wire   [18:0] select_ln339_12_fu_2843_p3;
wire   [16:0] select_ln318_40_fu_2876_p3;
wire   [3:0] tmp_32_fu_2914_p4;
wire   [9:0] tmp_11_fu_2904_p4;
wire   [18:0] select_ln318_43_fu_2897_p3;
wire   [16:0] select_ln318_42_fu_2890_p3;
wire   [16:0] trunc_ln708_20_fu_2924_p4;
wire   [0:0] icmp_ln1498_13_fu_2947_p2;
wire   [0:0] icmp_ln1494_22_fu_2953_p2;
wire   [16:0] select_ln318_41_fu_2883_p3;
wire   [16:0] mul_FL_V_3_fu_2933_p3;
wire   [0:0] icmp_ln1494_13_fu_2941_p2;
wire   [0:0] icmp_ln1496_4_fu_2971_p2;
wire   [0:0] or_ln318_29_fu_2977_p2;
wire   [0:0] icmp_ln318_12_fu_2965_p2;
wire   [0:0] icmp_ln1498_21_fu_3001_p2;
wire   [0:0] icmp_ln1495_12_fu_2995_p2;
wire   [0:0] and_ln331_4_fu_3007_p2;
wire   [16:0] p_neg_13_fu_3019_p3;
wire   [16:0] sub_ln703_24_fu_3027_p2;
wire   [0:0] or_ln331_4_fu_3013_p2;
wire   [18:0] add_ln703_19_fu_3039_p2;
wire   [0:0] or_ln318_20_fu_2983_p2;
wire   [0:0] and_ln318_13_fu_2959_p2;
wire   [0:0] xor_ln318_4_fu_3063_p2;
wire   [0:0] or_ln318_30_fu_3069_p2;
wire   [0:0] or_ln318_31_fu_3075_p2;
reg   [16:0] tmp_51_fu_3053_p4;
wire   [16:0] sub_ln703_23_fu_2989_p2;
wire   [16:0] add_ln703_18_fu_3033_p2;
wire   [18:0] select_ln339_13_fu_3045_p3;
wire   [16:0] trunc_ln708_21_fu_3133_p4;
wire   [0:0] icmp_ln1498_14_fu_3153_p2;
wire   [0:0] icmp_ln1494_23_fu_3158_p2;
wire   [16:0] mul_FL_V_4_fu_3141_p3;
wire   [0:0] icmp_ln1494_14_fu_3148_p2;
wire   [0:0] icmp_ln1496_5_fu_3174_p2;
wire   [0:0] or_ln318_32_fu_3179_p2;
wire   [0:0] icmp_ln318_13_fu_3169_p2;
wire   [0:0] icmp_ln1498_22_fu_3201_p2;
wire   [0:0] icmp_ln1495_13_fu_3196_p2;
wire   [0:0] and_ln331_5_fu_3206_p2;
wire   [16:0] p_neg_14_fu_3218_p3;
wire   [16:0] sub_ln703_26_fu_3226_p2;
wire   [0:0] or_ln331_5_fu_3212_p2;
wire   [18:0] add_ln703_21_fu_3237_p2;
wire   [0:0] or_ln318_21_fu_3185_p2;
wire   [0:0] and_ln318_14_fu_3163_p2;
wire   [0:0] xor_ln318_5_fu_3258_p2;
wire   [0:0] or_ln318_33_fu_3264_p2;
wire   [0:0] or_ln318_34_fu_3270_p2;
reg   [16:0] tmp_52_fu_3249_p4;
wire   [16:0] sub_ln703_25_fu_3191_p2;
wire   [16:0] add_ln703_20_fu_3232_p2;
wire   [18:0] select_ln339_14_fu_3242_p3;
wire   [1:0] tmp_34_fu_3314_p4;
wire   [13:0] tmp_13_fu_3304_p4;
wire   [16:0] trunc_ln708_22_fu_3324_p4;
wire   [0:0] icmp_ln1498_15_fu_3347_p2;
wire   [0:0] icmp_ln1494_24_fu_3353_p2;
wire   [0:0] icmp_ln1494_15_fu_3341_p2;
wire   [0:0] icmp_ln1496_6_fu_3371_p2;
wire   [0:0] or_ln318_35_fu_3377_p2;
wire   [0:0] icmp_ln318_14_fu_3365_p2;
wire   [0:0] icmp_ln1498_23_fu_3395_p2;
wire   [0:0] icmp_ln1495_14_fu_3389_p2;
wire   [0:0] and_ln331_6_fu_3401_p2;
wire   [16:0] p_neg_15_fu_3413_p3;
wire   [16:0] sub_ln703_28_fu_3421_p2;
wire   [0:0] or_ln331_6_fu_3407_p2;
wire   [18:0] add_ln703_23_fu_3433_p2;
wire   [0:0] or_ln318_22_fu_3383_p2;
wire   [0:0] and_ln318_15_fu_3359_p2;
wire   [0:0] xor_ln318_6_fu_3447_p2;
wire   [0:0] or_ln318_36_fu_3453_p2;
reg   [16:0] tmp_53_fu_3476_p4;
wire   [16:0] sub_ln703_27_fu_3472_p2;
wire   [16:0] select_ln318_52_fu_3485_p3;
wire   [15:0] trunc_ln103_fu_3507_p1;
wire   [0:0] tmp_54_fu_3519_p3;
wire   [18:0] select_ln318_55_fu_3502_p3;
wire   [16:0] select_ln318_54_fu_3497_p3;
wire   [16:0] trunc_ln708_23_fu_3527_p4;
wire   [0:0] icmp_ln1498_16_fu_3542_p2;
wire   [0:0] icmp_ln1494_25_fu_3548_p2;
wire   [16:0] select_ln318_53_fu_3491_p3;
wire   [16:0] mul_FL_V_6_fu_3511_p3;
wire   [0:0] icmp_ln1494_16_fu_3536_p2;
wire   [0:0] icmp_ln1496_7_fu_3566_p2;
wire   [0:0] or_ln318_38_fu_3572_p2;
wire   [0:0] icmp_ln318_15_fu_3560_p2;
wire   [0:0] or_ln318_23_fu_3578_p2;
wire   [0:0] and_ln318_16_fu_3554_p2;
wire   [0:0] xor_ln318_7_fu_3594_p2;
wire   [0:0] or_ln318_39_fu_3600_p2;
wire   [0:0] or_ln318_40_fu_3606_p2;
reg   [16:0] tmp_55_fu_3584_p4;
wire   [16:0] select_ln318_56_fu_3612_p3;
wire   [17:0] zext_ln1192_fu_3620_p1;
wire   [17:0] res_FH_l_V_fu_3624_p2;
wire   [0:0] p_Result_1_fu_3636_p3;
wire   [7:0] res_I_V_fu_3644_p2;
wire   [16:0] res_FH_V_fu_3630_p2;
wire   [7:0] p_Val2_s_fu_3649_p3;
wire   [15:0] tmp_35_fu_3656_p4;
wire   [0:0] p_Result_s_fu_3465_p3;
wire   [23:0] r_V_fu_3666_p3;
reg   [31:0] x_V_int_reg;

always @ (posedge ap_clk) begin
    x_V_int_reg <= x_V;
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        add_ln703_22_reg_4196 <= add_ln703_22_fu_3427_p2;
        icmp_ln1494_12_reg_4099 <= icmp_ln1494_12_fu_2755_p2;
        icmp_ln1494_21_reg_4110 <= icmp_ln1494_21_fu_2767_p2;
        icmp_ln1495_reg_3715 <= icmp_ln1495_fu_496_p2;
        icmp_ln1495_reg_3715_pp0_iter1_reg <= icmp_ln1495_reg_3715;
        icmp_ln1495_reg_3715_pp0_iter2_reg <= icmp_ln1495_reg_3715_pp0_iter1_reg;
        icmp_ln1496_3_reg_4120 <= icmp_ln1496_3_fu_2779_p2;
        icmp_ln1496_reg_4003 <= icmp_ln1496_fu_2195_p2;
        icmp_ln1498_12_reg_4105 <= icmp_ln1498_12_fu_2761_p2;
        icmp_ln318_11_reg_4115 <= icmp_ln318_11_fu_2773_p2;
        icmp_ln318_reg_3720 <= icmp_ln318_fu_512_p2;
        icmp_ln318_reg_3720_pp0_iter1_reg <= icmp_ln318_reg_3720;
        icmp_ln318_reg_3720_pp0_iter2_reg <= icmp_ln318_reg_3720_pp0_iter1_reg;
        icmp_ln488_2_reg_3704 <= icmp_ln488_2_fu_474_p2;
        icmp_ln488_5_reg_3737 <= icmp_ln488_5_fu_745_p2;
        icmp_ln488_7_reg_3754 <= icmp_ln488_7_fu_886_p2;
        mul_FL_V_2_reg_4094[16 : 9] <= mul_FL_V_2_fu_2747_p3[16 : 9];
        mul_FL_V_5_reg_4191[16 : 3] <= mul_FL_V_5_fu_3333_p3[16 : 3];
        or_ln318_12_reg_4009 <= or_ln318_12_fu_2231_p2;
        or_ln318_16_reg_4029 <= or_ln318_16_fu_2479_p2;
        or_ln318_1_reg_3793 <= or_ln318_1_fu_1137_p2;
        or_ln318_37_reg_4206 <= or_ln318_37_fu_3459_p2;
        or_ln318_3_reg_3887 <= or_ln318_3_fu_1473_p2;
        or_ln318_5_reg_3921 <= or_ln318_5_fu_1727_p2;
        or_ln318_7_reg_3961 <= or_ln318_7_fu_1971_p2;
        p_Result_34_2_reg_3812 <= {{select_ln318_3_fu_1143_p3[16:14]}};
        p_Result_34_4_reg_3906 <= {{select_ln318_9_fu_1479_p3[16:12]}};
        p_Result_34_6_reg_3940 <= {{select_ln318_15_fu_1733_p3[16:10]}};
        select_ln318_10_reg_3898[16 : 1] <= select_ln318_10_fu_1487_p3[16 : 1];
        select_ln318_14_reg_3911 <= select_ln318_14_fu_1617_p3;
        select_ln318_15_reg_3926 <= select_ln318_15_fu_1733_p3;
        select_ln318_16_reg_3932[16 : 1] <= select_ln318_16_fu_1741_p3[16 : 1];
        select_ln318_18_reg_3945 <= select_ln318_18_fu_1857_p3;
        select_ln318_20_reg_3951 <= select_ln318_20_fu_1871_p3;
        select_ln318_22_reg_3967[16 : 1] <= select_ln318_22_fu_1977_p3[16 : 1];
        select_ln318_24_reg_3975 <= select_ln318_24_fu_2097_p3;
        select_ln318_26_reg_3981 <= select_ln318_26_fu_2113_p3;
        select_ln318_27_reg_3989 <= select_ln318_27_fu_2120_p3;
        select_ln318_28_reg_4023 <= select_ln318_28_fu_2302_p3;
        select_ln318_29_reg_4016[16 : 14] <= select_ln318_29_fu_2237_p3[16 : 14];
        select_ln318_2_reg_3783 <= select_ln318_2_fu_1012_p3;
        select_ln318_33_reg_4034[16 : 12] <= select_ln318_33_fu_2485_p3[16 : 12];
        select_ln318_34_reg_4041 <= select_ln318_34_fu_2492_p3;
        select_ln318_35_reg_4051 <= select_ln318_35_fu_2500_p3;
        select_ln318_36_reg_4060 <= select_ln318_36_fu_2689_p3;
        select_ln318_37_reg_4066[16 : 10] <= select_ln318_37_fu_2697_p3[16 : 10];
        select_ln318_38_reg_4072 <= select_ln318_38_fu_2704_p3;
        select_ln318_39_reg_4080 <= select_ln318_39_fu_2711_p3;
        select_ln318_3_reg_3798 <= select_ln318_3_fu_1143_p3;
        select_ln318_44_reg_4127 <= select_ln318_44_fu_3081_p3;
        select_ln318_45_reg_4133[16 : 6] <= select_ln318_45_fu_3089_p3[16 : 6];
        select_ln318_46_reg_4140 <= select_ln318_46_fu_3097_p3;
        select_ln318_47_reg_4150 <= select_ln318_47_fu_3105_p3;
        select_ln318_48_reg_4169 <= select_ln318_48_fu_3276_p3;
        select_ln318_49_reg_4175[16 : 4] <= select_ln318_49_fu_3283_p3[16 : 4];
        select_ln318_4_reg_3804[16 : 1] <= select_ln318_4_fu_1151_p3[16 : 1];
        select_ln318_50_reg_4181 <= select_ln318_50_fu_3290_p3;
        select_ln318_51_reg_4186 <= select_ln318_51_fu_3297_p3;
        select_ln318_8_reg_3877 <= select_ln318_8_fu_1363_p3;
        select_ln318_9_reg_3892 <= select_ln318_9_fu_1479_p3;
        select_ln339_15_reg_4201 <= select_ln339_15_fu_3439_p3;
        select_ln488_12_reg_3748 <= select_ln488_12_fu_854_p3;
        select_ln488_14_reg_3768 <= select_ln488_14_fu_934_p3;
        select_ln488_14_reg_3768_pp0_iter10_reg <= select_ln488_14_reg_3768_pp0_iter9_reg;
        select_ln488_14_reg_3768_pp0_iter11_reg <= select_ln488_14_reg_3768_pp0_iter10_reg;
        select_ln488_14_reg_3768_pp0_iter4_reg <= select_ln488_14_reg_3768;
        select_ln488_14_reg_3768_pp0_iter5_reg <= select_ln488_14_reg_3768_pp0_iter4_reg;
        select_ln488_14_reg_3768_pp0_iter6_reg <= select_ln488_14_reg_3768_pp0_iter5_reg;
        select_ln488_14_reg_3768_pp0_iter7_reg <= select_ln488_14_reg_3768_pp0_iter6_reg;
        select_ln488_14_reg_3768_pp0_iter8_reg <= select_ln488_14_reg_3768_pp0_iter7_reg;
        select_ln488_14_reg_3768_pp0_iter9_reg <= select_ln488_14_reg_3768_pp0_iter8_reg;
        select_ln488_15_reg_3759 <= select_ln488_15_fu_910_p3;
        select_ln488_2_reg_3692 <= select_ln488_2_fu_426_p3;
        select_ln488_3_reg_3698 <= select_ln488_3_fu_434_p3;
        select_ln488_8_reg_3725 <= select_ln488_8_fu_697_p3;
        select_ln488_9_reg_3731 <= select_ln488_9_fu_705_p3;
        sub_ln248_1_reg_3710 <= sub_ln248_1_fu_480_p2;
        sub_ln248_4_reg_3743 <= sub_ln248_4_fu_751_p2;
        sub_ln703_10_reg_3916 <= sub_ln703_10_fu_1693_p2;
        sub_ln703_14_reg_3956 <= sub_ln703_14_fu_1947_p2;
        sub_ln703_2_reg_3788 <= sub_ln703_2_fu_1103_p2;
        sub_ln703_6_reg_3882 <= sub_ln703_6_fu_1439_p2;
        tmp_12_reg_4159 <= {{select_ln318_44_fu_3081_p3[13:2]}};
        tmp_15_reg_3817 <= {{select_ln488_14_fu_934_p3[7:2]}};
        tmp_17_reg_3827 <= {{select_ln488_14_fu_934_p3[7:3]}};
        tmp_19_reg_3837 <= {{select_ln488_14_fu_934_p3[7:4]}};
        tmp_19_reg_3837_pp0_iter4_reg <= tmp_19_reg_3837;
        tmp_21_reg_3847 <= {{select_ln488_14_fu_934_p3[7:5]}};
        tmp_21_reg_3847_pp0_iter4_reg <= tmp_21_reg_3847;
        tmp_23_reg_3857 <= {{select_ln488_14_fu_934_p3[7:6]}};
        tmp_23_reg_3857_pp0_iter4_reg <= tmp_23_reg_3857;
        tmp_23_reg_3857_pp0_iter5_reg <= tmp_23_reg_3857_pp0_iter4_reg;
        tmp_33_reg_4164 <= {{select_ln318_44_fu_3081_p3[16:14]}};
        tmp_44_reg_3867 <= select_ln488_14_fu_934_p3[32'd7];
        tmp_44_reg_3867_pp0_iter4_reg <= tmp_44_reg_3867;
        tmp_44_reg_3867_pp0_iter5_reg <= tmp_44_reg_3867_pp0_iter4_reg;
        trunc_ln708_16_reg_3996[15 : 0] <= trunc_ln708_16_fu_2148_p4[15 : 0];
        trunc_ln708_19_reg_4087[12 : 0] <= trunc_ln708_19_fu_2738_p4[12 : 0];
        trunc_ln708_24_reg_3822 <= trunc_ln708_24_fu_1179_p1;
        trunc_ln708_25_reg_3832 <= trunc_ln708_25_fu_1193_p1;
        trunc_ln708_26_reg_3842 <= trunc_ln708_26_fu_1207_p1;
        trunc_ln708_26_reg_3842_pp0_iter4_reg <= trunc_ln708_26_reg_3842;
        trunc_ln708_27_reg_3852 <= trunc_ln708_27_fu_1221_p1;
        trunc_ln708_27_reg_3852_pp0_iter4_reg <= trunc_ln708_27_reg_3852;
        trunc_ln708_28_reg_3862 <= trunc_ln708_28_fu_1235_p1;
        trunc_ln708_28_reg_3862_pp0_iter4_reg <= trunc_ln708_28_reg_3862;
        trunc_ln708_28_reg_3862_pp0_iter5_reg <= trunc_ln708_28_reg_3862_pp0_iter4_reg;
        trunc_ln708_29_reg_3872 <= trunc_ln708_29_fu_1247_p1;
        trunc_ln708_29_reg_3872_pp0_iter4_reg <= trunc_ln708_29_reg_3872;
        trunc_ln708_29_reg_3872_pp0_iter5_reg <= trunc_ln708_29_reg_3872_pp0_iter4_reg;
        trunc_ln731_reg_3687 <= trunc_ln731_fu_302_p1;
        trunc_ln731_reg_3687_pp0_iter1_reg <= trunc_ln731_reg_3687;
        trunc_ln731_reg_3687_pp0_iter2_reg <= trunc_ln731_reg_3687_pp0_iter1_reg;
        x_V_read_reg_3682 <= x_V_int_reg;
        x_V_read_reg_3682_pp0_iter10_reg <= x_V_read_reg_3682_pp0_iter9_reg;
        x_V_read_reg_3682_pp0_iter11_reg <= x_V_read_reg_3682_pp0_iter10_reg;
        x_V_read_reg_3682_pp0_iter1_reg <= x_V_read_reg_3682;
        x_V_read_reg_3682_pp0_iter2_reg <= x_V_read_reg_3682_pp0_iter1_reg;
        x_V_read_reg_3682_pp0_iter3_reg <= x_V_read_reg_3682_pp0_iter2_reg;
        x_V_read_reg_3682_pp0_iter4_reg <= x_V_read_reg_3682_pp0_iter3_reg;
        x_V_read_reg_3682_pp0_iter5_reg <= x_V_read_reg_3682_pp0_iter4_reg;
        x_V_read_reg_3682_pp0_iter6_reg <= x_V_read_reg_3682_pp0_iter5_reg;
        x_V_read_reg_3682_pp0_iter7_reg <= x_V_read_reg_3682_pp0_iter6_reg;
        x_V_read_reg_3682_pp0_iter8_reg <= x_V_read_reg_3682_pp0_iter7_reg;
        x_V_read_reg_3682_pp0_iter9_reg <= x_V_read_reg_3682_pp0_iter8_reg;
    end
end

assign add_ln248_fu_326_p2 = ($signed(zext_ln248_fu_316_p1) + $signed(3'd7));

assign add_ln703_10_fu_2276_p2 = (sub_ln703_16_fu_2271_p2 + select_ln318_26_reg_3981);

assign add_ln703_11_fu_2281_p2 = ($signed(select_ln318_27_reg_3989) + $signed(19'd524287));

assign add_ln703_12_fu_2447_p2 = (sub_ln703_18_fu_2441_p2 + select_ln318_30_fu_2308_p3);

assign add_ln703_13_fu_2453_p2 = ($signed(select_ln318_31_fu_2314_p3) + $signed(19'd524287));

assign add_ln703_14_fu_2644_p2 = (sub_ln703_20_fu_2638_p2 + select_ln318_34_reg_4041);

assign add_ln703_15_fu_2649_p2 = ($signed(select_ln318_35_reg_4051) + $signed(19'd524287));

assign add_ln703_16_fu_2833_p2 = (sub_ln703_22_fu_2828_p2 + select_ln318_38_reg_4072);

assign add_ln703_17_fu_2838_p2 = ($signed(select_ln318_39_reg_4080) + $signed(19'd524287));

assign add_ln703_18_fu_3033_p2 = (sub_ln703_24_fu_3027_p2 + select_ln318_42_fu_2890_p3);

assign add_ln703_19_fu_3039_p2 = ($signed(select_ln318_43_fu_2897_p3) + $signed(19'd524287));

assign add_ln703_1_fu_1089_p2 = ($signed(select_ln318_2_fu_1012_p3) + $signed(19'd524287));

assign add_ln703_20_fu_3232_p2 = (sub_ln703_26_fu_3226_p2 + select_ln318_46_reg_4140);

assign add_ln703_21_fu_3237_p2 = ($signed(select_ln318_47_reg_4150) + $signed(19'd524287));

assign add_ln703_22_fu_3427_p2 = (sub_ln703_28_fu_3421_p2 + select_ln318_50_fu_3290_p3);

assign add_ln703_23_fu_3433_p2 = ($signed(select_ln318_51_fu_3297_p3) + $signed(19'd524287));

assign add_ln703_24_fu_962_p2 = ($signed(x_l_FH_V_fu_918_p3) + $signed(17'd98304));

assign add_ln703_2_fu_1297_p2 = ($signed(select_ln318_5_fu_1251_p3) + $signed(19'd524287));

assign add_ln703_3_fu_1425_p2 = ($signed(select_ln318_8_fu_1363_p3) + $signed(19'd524287));

assign add_ln703_4_fu_1551_p2 = ($signed(select_ln318_11_fu_1505_p3) + $signed(19'd524287));

assign add_ln703_5_fu_1679_p2 = ($signed(select_ln318_14_fu_1617_p3) + $signed(19'd524287));

assign add_ln703_6_fu_1805_p2 = ($signed(select_ln318_17_fu_1759_p3) + $signed(19'd524287));

assign add_ln703_7_fu_1933_p2 = ($signed(select_ln318_20_fu_1871_p3) + $signed(19'd524287));

assign add_ln703_8_fu_2062_p2 = (select_ln318_22_reg_3967 + xor_ln703_fu_2056_p2);

assign add_ln703_9_fu_2067_p2 = ($signed(select_ln318_23_fu_2000_p3) + $signed(19'd524287));

assign add_ln703_fu_968_p2 = ($signed(select_ln488_15_reg_3759) + $signed(19'd524287));

assign and_ln318_10_fu_2375_p2 = (icmp_ln1498_10_fu_2363_p2 & icmp_ln1494_19_fu_2369_p2);

assign and_ln318_11_fu_2575_p2 = (icmp_ln1498_11_fu_2565_p2 & icmp_ln1494_20_fu_2570_p2);

assign and_ln318_12_fu_2785_p2 = (icmp_ln1498_12_reg_4105 & icmp_ln1494_21_reg_4110);

assign and_ln318_13_fu_2959_p2 = (icmp_ln1498_13_fu_2947_p2 & icmp_ln1494_22_fu_2953_p2);

assign and_ln318_14_fu_3163_p2 = (icmp_ln1498_14_fu_3153_p2 & icmp_ln1494_23_fu_3158_p2);

assign and_ln318_15_fu_3359_p2 = (icmp_ln1498_15_fu_3347_p2 & icmp_ln1494_24_fu_3353_p2);

assign and_ln318_16_fu_3554_p2 = (icmp_ln1498_16_fu_3542_p2 & icmp_ln1494_25_fu_3548_p2);

assign and_ln318_1_fu_1131_p2 = (xor_ln318_8_fu_1125_p2 & icmp_ln1498_1_fu_1071_p2);

assign and_ln318_2_fu_1337_p2 = (xor_ln318_9_fu_1331_p2 & icmp_ln1498_2_fu_1281_p2);

assign and_ln318_3_fu_1467_p2 = (xor_ln318_10_fu_1461_p2 & icmp_ln1498_3_fu_1407_p2);

assign and_ln318_4_fu_1591_p2 = (xor_ln318_11_fu_1585_p2 & icmp_ln1498_4_fu_1535_p2);

assign and_ln318_5_fu_1721_p2 = (xor_ln318_12_fu_1715_p2 & icmp_ln1498_5_fu_1661_p2);

assign and_ln318_6_fu_1845_p2 = (xor_ln318_13_fu_1839_p2 & icmp_ln1498_6_fu_1789_p2);

assign and_ln318_7_fu_1965_p2 = (xor_ln318_14_fu_1959_p2 & icmp_ln1498_7_fu_1915_p2);

assign and_ln318_8_fu_2039_p2 = (icmp_ln1498_8_fu_2028_p2 & icmp_ln1494_17_fu_2034_p2);

assign and_ln318_9_fu_2183_p2 = (icmp_ln1498_9_fu_2171_p2 & icmp_ln1494_18_fu_2177_p2);

assign and_ln318_fu_985_p2 = (icmp_ln318_reg_3720_pp0_iter2_reg & icmp_ln1498_fu_957_p2);

assign and_ln331_1_fu_2421_p2 = (icmp_ln1498_18_fu_2415_p2 & icmp_ln1496_1_fu_2387_p2);

assign and_ln331_2_fu_2618_p2 = (icmp_ln1498_19_fu_2613_p2 & icmp_ln1496_2_fu_2586_p2);

assign and_ln331_3_fu_2810_p2 = (icmp_ln1498_20_fu_2806_p2 & icmp_ln1496_3_reg_4120);

assign and_ln331_4_fu_3007_p2 = (icmp_ln1498_21_fu_3001_p2 & icmp_ln1496_4_fu_2971_p2);

assign and_ln331_5_fu_3206_p2 = (icmp_ln1498_22_fu_3201_p2 & icmp_ln1496_5_fu_3174_p2);

assign and_ln331_6_fu_3401_p2 = (icmp_ln1498_23_fu_3395_p2 & icmp_ln1496_6_fu_3371_p2);

assign and_ln331_fu_2253_p2 = (icmp_ln1498_17_fu_2249_p2 & icmp_ln1496_reg_4003);

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_state10_pp0_stage0_iter9 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp0_stage0_iter10 = ~(1'b1 == 1'b1);

assign ap_block_state12_pp0_stage0_iter11 = ~(1'b1 == 1'b1);

assign ap_block_state13_pp0_stage0_iter12 = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage0_iter7 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage0_iter8 = ~(1'b1 == 1'b1);

assign ap_ext_blocking_n = (1'b1 & 1'b1);

assign ap_int_blocking_n = (1'b1 & 1'b1);

assign ap_return = ((p_Result_s_fu_3465_p3[0:0] === 1'b1) ? 24'd0 : r_V_fu_3666_p3);

assign ap_str_blocking_n = (1'b1 & 1'b1);

assign icmp_ln1494_10_fu_2357_p2 = ((select_ln318_31_fu_2314_p3 != 19'd0) ? 1'b1 : 1'b0);

assign icmp_ln1494_11_fu_2560_p2 = ((select_ln318_35_reg_4051 != 19'd0) ? 1'b1 : 1'b0);

assign icmp_ln1494_12_fu_2755_p2 = ((select_ln318_39_fu_2711_p3 != 19'd0) ? 1'b1 : 1'b0);

assign icmp_ln1494_13_fu_2941_p2 = ((select_ln318_43_fu_2897_p3 != 19'd0) ? 1'b1 : 1'b0);

assign icmp_ln1494_14_fu_3148_p2 = ((select_ln318_47_reg_4150 != 19'd0) ? 1'b1 : 1'b0);

assign icmp_ln1494_15_fu_3341_p2 = ((select_ln318_51_fu_3297_p3 != 19'd0) ? 1'b1 : 1'b0);

assign icmp_ln1494_16_fu_3536_p2 = ((select_ln318_55_fu_3502_p3 != 19'd0) ? 1'b1 : 1'b0);

assign icmp_ln1494_17_fu_2034_p2 = ((select_ln318_22_reg_3967 > trunc_ln708_15_fu_2015_p3) ? 1'b1 : 1'b0);

assign icmp_ln1494_18_fu_2177_p2 = ((select_ln318_26_fu_2113_p3 > trunc_ln708_16_fu_2148_p4) ? 1'b1 : 1'b0);

assign icmp_ln1494_19_fu_2369_p2 = ((select_ln318_30_fu_2308_p3 > trunc_ln708_17_fu_2340_p4) ? 1'b1 : 1'b0);

assign icmp_ln1494_1_fu_1065_p2 = ((select_ln318_2_fu_1012_p3 > zext_ln1494_1_fu_1061_p1) ? 1'b1 : 1'b0);

assign icmp_ln1494_20_fu_2570_p2 = ((select_ln318_34_reg_4041 > trunc_ln708_18_fu_2543_p4) ? 1'b1 : 1'b0);

assign icmp_ln1494_21_fu_2767_p2 = ((select_ln318_38_fu_2704_p3 > trunc_ln708_19_fu_2738_p4) ? 1'b1 : 1'b0);

assign icmp_ln1494_22_fu_2953_p2 = ((select_ln318_42_fu_2890_p3 > trunc_ln708_20_fu_2924_p4) ? 1'b1 : 1'b0);

assign icmp_ln1494_23_fu_3158_p2 = ((select_ln318_46_reg_4140 > trunc_ln708_21_fu_3133_p4) ? 1'b1 : 1'b0);

assign icmp_ln1494_24_fu_3353_p2 = ((select_ln318_50_fu_3290_p3 > trunc_ln708_22_fu_3324_p4) ? 1'b1 : 1'b0);

assign icmp_ln1494_25_fu_3548_p2 = ((select_ln318_54_fu_3497_p3 > trunc_ln708_23_fu_3527_p4) ? 1'b1 : 1'b0);

assign icmp_ln1494_2_fu_1275_p2 = ((select_ln318_5_fu_1251_p3 > zext_ln1494_2_fu_1271_p1) ? 1'b1 : 1'b0);

assign icmp_ln1494_3_fu_1401_p2 = ((select_ln318_8_fu_1363_p3 > zext_ln1494_3_fu_1397_p1) ? 1'b1 : 1'b0);

assign icmp_ln1494_4_fu_1529_p2 = ((select_ln318_11_fu_1505_p3 > zext_ln1494_4_fu_1525_p1) ? 1'b1 : 1'b0);

assign icmp_ln1494_5_fu_1655_p2 = ((select_ln318_14_fu_1617_p3 > zext_ln1494_5_fu_1651_p1) ? 1'b1 : 1'b0);

assign icmp_ln1494_6_fu_1783_p2 = ((select_ln318_17_fu_1759_p3 > zext_ln1494_6_fu_1779_p1) ? 1'b1 : 1'b0);

assign icmp_ln1494_7_fu_1909_p2 = ((select_ln318_20_fu_1871_p3 > zext_ln1494_7_fu_1905_p1) ? 1'b1 : 1'b0);

assign icmp_ln1494_8_fu_2022_p2 = ((select_ln318_23_fu_2000_p3 != 19'd0) ? 1'b1 : 1'b0);

assign icmp_ln1494_9_fu_2165_p2 = ((select_ln318_27_fu_2120_p3 != 19'd0) ? 1'b1 : 1'b0);

assign icmp_ln1494_fu_952_p2 = ((select_ln488_15_reg_3759 > zext_ln1494_fu_948_p1) ? 1'b1 : 1'b0);

assign icmp_ln1495_10_fu_2608_p2 = ((select_ln318_34_reg_4041 < trunc_ln708_18_fu_2543_p4) ? 1'b1 : 1'b0);

assign icmp_ln1495_11_fu_2802_p2 = ((select_ln318_38_reg_4072 < trunc_ln708_19_reg_4087) ? 1'b1 : 1'b0);

assign icmp_ln1495_12_fu_2995_p2 = ((select_ln318_42_fu_2890_p3 < trunc_ln708_20_fu_2924_p4) ? 1'b1 : 1'b0);

assign icmp_ln1495_13_fu_3196_p2 = ((select_ln318_46_reg_4140 < trunc_ln708_21_fu_3133_p4) ? 1'b1 : 1'b0);

assign icmp_ln1495_14_fu_3389_p2 = ((select_ln318_50_fu_3290_p3 < trunc_ln708_22_fu_3324_p4) ? 1'b1 : 1'b0);

assign icmp_ln1495_1_fu_1077_p2 = ((select_ln318_1_fu_1004_p3 < trunc_ln708_4_fu_1051_p4) ? 1'b1 : 1'b0);

assign icmp_ln1495_2_fu_1287_p2 = ((select_ln318_4_reg_3804 < trunc_ln708_6_fu_1263_p4) ? 1'b1 : 1'b0);

assign icmp_ln1495_3_fu_1413_p2 = ((select_ln318_7_fu_1356_p3 < trunc_ln708_8_fu_1388_p4) ? 1'b1 : 1'b0);

assign icmp_ln1495_4_fu_1541_p2 = ((select_ln318_10_reg_3898 < trunc_ln708_s_fu_1517_p4) ? 1'b1 : 1'b0);

assign icmp_ln1495_5_fu_1667_p2 = ((select_ln318_13_fu_1610_p3 < trunc_ln708_10_fu_1642_p4) ? 1'b1 : 1'b0);

assign icmp_ln1495_6_fu_1795_p2 = ((select_ln318_16_reg_3932 < trunc_ln708_12_fu_1771_p4) ? 1'b1 : 1'b0);

assign icmp_ln1495_7_fu_1921_p2 = ((select_ln318_19_fu_1864_p3 < trunc_ln708_14_fu_1896_p4) ? 1'b1 : 1'b0);

assign icmp_ln1495_8_fu_2245_p2 = ((select_ln318_26_reg_3981 < trunc_ln708_16_reg_3996) ? 1'b1 : 1'b0);

assign icmp_ln1495_9_fu_2409_p2 = ((select_ln318_30_fu_2308_p3 < trunc_ln708_17_fu_2340_p4) ? 1'b1 : 1'b0);

assign icmp_ln1495_fu_496_p2 = ((tmp_28_fu_486_p4 == 2'd0) ? 1'b1 : 1'b0);

assign icmp_ln1496_1_fu_2387_p2 = ((select_ln318_29_reg_4016 < mul_FL_V_s_fu_2349_p3) ? 1'b1 : 1'b0);

assign icmp_ln1496_2_fu_2586_p2 = ((select_ln318_33_reg_4034 < mul_FL_V_1_fu_2552_p3) ? 1'b1 : 1'b0);

assign icmp_ln1496_3_fu_2779_p2 = ((select_ln318_37_fu_2697_p3 < mul_FL_V_2_fu_2747_p3) ? 1'b1 : 1'b0);

assign icmp_ln1496_4_fu_2971_p2 = ((select_ln318_41_fu_2883_p3 < mul_FL_V_3_fu_2933_p3) ? 1'b1 : 1'b0);

assign icmp_ln1496_5_fu_3174_p2 = ((select_ln318_45_reg_4133 < mul_FL_V_4_fu_3141_p3) ? 1'b1 : 1'b0);

assign icmp_ln1496_6_fu_3371_p2 = ((select_ln318_49_fu_3283_p3 < mul_FL_V_5_fu_3333_p3) ? 1'b1 : 1'b0);

assign icmp_ln1496_7_fu_3566_p2 = ((select_ln318_53_fu_3491_p3 < mul_FL_V_6_fu_3511_p3) ? 1'b1 : 1'b0);

assign icmp_ln1496_fu_2195_p2 = ((select_ln318_25_fu_2105_p3 < mul_FL_V_9_fu_2157_p3) ? 1'b1 : 1'b0);

assign icmp_ln1498_10_fu_2363_p2 = ((select_ln318_31_fu_2314_p3 == 19'd0) ? 1'b1 : 1'b0);

assign icmp_ln1498_11_fu_2565_p2 = ((select_ln318_35_reg_4051 == 19'd0) ? 1'b1 : 1'b0);

assign icmp_ln1498_12_fu_2761_p2 = ((select_ln318_39_fu_2711_p3 == 19'd0) ? 1'b1 : 1'b0);

assign icmp_ln1498_13_fu_2947_p2 = ((select_ln318_43_fu_2897_p3 == 19'd0) ? 1'b1 : 1'b0);

assign icmp_ln1498_14_fu_3153_p2 = ((select_ln318_47_reg_4150 == 19'd0) ? 1'b1 : 1'b0);

assign icmp_ln1498_15_fu_3347_p2 = ((select_ln318_51_fu_3297_p3 == 19'd0) ? 1'b1 : 1'b0);

assign icmp_ln1498_16_fu_3542_p2 = ((select_ln318_55_fu_3502_p3 == 19'd0) ? 1'b1 : 1'b0);

assign icmp_ln1498_17_fu_2249_p2 = ((select_ln318_26_reg_3981 == trunc_ln708_16_reg_3996) ? 1'b1 : 1'b0);

assign icmp_ln1498_18_fu_2415_p2 = ((select_ln318_30_fu_2308_p3 == trunc_ln708_17_fu_2340_p4) ? 1'b1 : 1'b0);

assign icmp_ln1498_19_fu_2613_p2 = ((select_ln318_34_reg_4041 == trunc_ln708_18_fu_2543_p4) ? 1'b1 : 1'b0);

assign icmp_ln1498_1_fu_1071_p2 = ((select_ln318_2_fu_1012_p3 == zext_ln1494_1_fu_1061_p1) ? 1'b1 : 1'b0);

assign icmp_ln1498_20_fu_2806_p2 = ((select_ln318_38_reg_4072 == trunc_ln708_19_reg_4087) ? 1'b1 : 1'b0);

assign icmp_ln1498_21_fu_3001_p2 = ((select_ln318_42_fu_2890_p3 == trunc_ln708_20_fu_2924_p4) ? 1'b1 : 1'b0);

assign icmp_ln1498_22_fu_3201_p2 = ((select_ln318_46_reg_4140 == trunc_ln708_21_fu_3133_p4) ? 1'b1 : 1'b0);

assign icmp_ln1498_23_fu_3395_p2 = ((select_ln318_50_fu_3290_p3 == trunc_ln708_22_fu_3324_p4) ? 1'b1 : 1'b0);

assign icmp_ln1498_2_fu_1281_p2 = ((select_ln318_5_fu_1251_p3 == zext_ln1494_2_fu_1271_p1) ? 1'b1 : 1'b0);

assign icmp_ln1498_3_fu_1407_p2 = ((select_ln318_8_fu_1363_p3 == zext_ln1494_3_fu_1397_p1) ? 1'b1 : 1'b0);

assign icmp_ln1498_4_fu_1535_p2 = ((select_ln318_11_fu_1505_p3 == zext_ln1494_4_fu_1525_p1) ? 1'b1 : 1'b0);

assign icmp_ln1498_5_fu_1661_p2 = ((select_ln318_14_fu_1617_p3 == zext_ln1494_5_fu_1651_p1) ? 1'b1 : 1'b0);

assign icmp_ln1498_6_fu_1789_p2 = ((select_ln318_17_fu_1759_p3 == zext_ln1494_6_fu_1779_p1) ? 1'b1 : 1'b0);

assign icmp_ln1498_7_fu_1915_p2 = ((select_ln318_20_fu_1871_p3 == zext_ln1494_7_fu_1905_p1) ? 1'b1 : 1'b0);

assign icmp_ln1498_8_fu_2028_p2 = ((select_ln318_23_fu_2000_p3 == 19'd0) ? 1'b1 : 1'b0);

assign icmp_ln1498_9_fu_2171_p2 = ((select_ln318_27_fu_2120_p3 == 19'd0) ? 1'b1 : 1'b0);

assign icmp_ln1498_fu_957_p2 = ((select_ln488_15_reg_3759 == zext_ln1494_fu_948_p1) ? 1'b1 : 1'b0);

assign icmp_ln318_10_fu_2581_p2 = ((select_ln318_34_reg_4041 != trunc_ln708_18_fu_2543_p4) ? 1'b1 : 1'b0);

assign icmp_ln318_11_fu_2773_p2 = ((select_ln318_38_fu_2704_p3 != trunc_ln708_19_fu_2738_p4) ? 1'b1 : 1'b0);

assign icmp_ln318_12_fu_2965_p2 = ((select_ln318_42_fu_2890_p3 != trunc_ln708_20_fu_2924_p4) ? 1'b1 : 1'b0);

assign icmp_ln318_13_fu_3169_p2 = ((select_ln318_46_reg_4140 != trunc_ln708_21_fu_3133_p4) ? 1'b1 : 1'b0);

assign icmp_ln318_14_fu_3365_p2 = ((select_ln318_50_fu_3290_p3 != trunc_ln708_22_fu_3324_p4) ? 1'b1 : 1'b0);

assign icmp_ln318_15_fu_3560_p2 = ((select_ln318_54_fu_3497_p3 != trunc_ln708_23_fu_3527_p4) ? 1'b1 : 1'b0);

assign icmp_ln318_1_fu_1119_p2 = ((select_ln318_1_fu_1004_p3 < trunc_ln708_4_fu_1051_p4) ? 1'b1 : 1'b0);

assign icmp_ln318_2_fu_1326_p2 = ((select_ln318_4_reg_3804 < trunc_ln708_6_fu_1263_p4) ? 1'b1 : 1'b0);

assign icmp_ln318_3_fu_1455_p2 = ((select_ln318_7_fu_1356_p3 < trunc_ln708_8_fu_1388_p4) ? 1'b1 : 1'b0);

assign icmp_ln318_4_fu_1580_p2 = ((select_ln318_10_reg_3898 < trunc_ln708_s_fu_1517_p4) ? 1'b1 : 1'b0);

assign icmp_ln318_5_fu_1709_p2 = ((select_ln318_13_fu_1610_p3 < trunc_ln708_10_fu_1642_p4) ? 1'b1 : 1'b0);

assign icmp_ln318_6_fu_1834_p2 = ((select_ln318_16_reg_3932 < trunc_ln708_12_fu_1771_p4) ? 1'b1 : 1'b0);

assign icmp_ln318_7_fu_1953_p2 = ((select_ln318_19_fu_1864_p3 < trunc_ln708_14_fu_1896_p4) ? 1'b1 : 1'b0);

assign icmp_ln318_8_fu_2189_p2 = ((select_ln318_26_fu_2113_p3 != trunc_ln708_16_fu_2148_p4) ? 1'b1 : 1'b0);

assign icmp_ln318_9_fu_2381_p2 = ((select_ln318_30_fu_2308_p3 != trunc_ln708_17_fu_2340_p4) ? 1'b1 : 1'b0);

assign icmp_ln318_fu_512_p2 = ((tmp_36_fu_502_p4 != 2'd0) ? 1'b1 : 1'b0);

assign icmp_ln331_fu_2045_p2 = ((trunc_ln708_15_fu_2015_p3 < select_ln318_22_reg_3967) ? 1'b1 : 1'b0);

assign icmp_ln488_1_fu_392_p2 = ((p_Result_28_1_fu_378_p4 < zext_ln488_fu_388_p1) ? 1'b1 : 1'b0);

assign icmp_ln488_2_fu_474_p2 = ((p_Result_28_2_fu_460_p4 < zext_ln488_1_fu_470_p1) ? 1'b1 : 1'b0);

assign icmp_ln488_3_fu_581_p2 = ((p_Result_28_3_fu_567_p4 < zext_ln488_2_fu_577_p1) ? 1'b1 : 1'b0);

assign icmp_ln488_4_fu_663_p2 = ((p_Result_28_4_fu_649_p4 < zext_ln488_3_fu_659_p1) ? 1'b1 : 1'b0);

assign icmp_ln488_5_fu_745_p2 = ((p_Result_28_5_fu_731_p4 < zext_ln488_4_fu_741_p1) ? 1'b1 : 1'b0);

assign icmp_ln488_6_fu_820_p2 = ((p_Result_28_6_fu_806_p4 < zext_ln488_5_fu_816_p1) ? 1'b1 : 1'b0);

assign icmp_ln488_7_fu_886_p2 = ((trunc_ln612_fu_878_p1 < zext_ln488_6_fu_882_p1) ? 1'b1 : 1'b0);

assign icmp_ln488_fu_320_p2 = ((tmp_fu_306_p4 == 2'd0) ? 1'b1 : 1'b0);

assign mul_FL_V_1_fu_2552_p3 = {{tmp_s_fu_2523_p4}, {11'd1024}};

assign mul_FL_V_2_fu_2747_p3 = {{tmp_10_fu_2718_p4}, {9'd256}};

assign mul_FL_V_3_fu_2933_p3 = {{tmp_11_fu_2904_p4}, {7'd64}};

assign mul_FL_V_4_fu_3141_p3 = {{tmp_12_reg_4159}, {5'd16}};

assign mul_FL_V_5_fu_3333_p3 = {{tmp_13_fu_3304_p4}, {3'd4}};

assign mul_FL_V_6_fu_3511_p3 = {{trunc_ln103_fu_3507_p1}, {1'd1}};

assign mul_FL_V_9_fu_2157_p3 = {{tmp_8_fu_2128_p4}, {15'd16384}};

assign mul_FL_V_s_fu_2349_p3 = {{tmp_9_fu_2320_p4}, {13'd4096}};

assign or_ln318_10_fu_2201_p2 = (icmp_ln1496_fu_2195_p2 | icmp_ln1494_9_fu_2165_p2);

assign or_ln318_11_fu_2225_p2 = (xor_ln318_fu_2219_p2 | and_ln318_9_fu_2183_p2);

assign or_ln318_12_fu_2231_p2 = (or_ln318_11_fu_2225_p2 | icmp_ln1494_9_fu_2165_p2);

assign or_ln318_13_fu_2392_p2 = (icmp_ln1496_1_fu_2387_p2 | icmp_ln1494_10_fu_2357_p2);

assign or_ln318_14_fu_2398_p2 = (or_ln318_13_fu_2392_p2 | icmp_ln318_9_fu_2381_p2);

assign or_ln318_15_fu_2473_p2 = (xor_ln318_1_fu_2467_p2 | and_ln318_10_fu_2375_p2);

assign or_ln318_16_fu_2479_p2 = (or_ln318_15_fu_2473_p2 | icmp_ln1494_10_fu_2357_p2);

assign or_ln318_17_fu_2591_p2 = (icmp_ln1496_2_fu_2586_p2 | icmp_ln1494_11_fu_2560_p2);

assign or_ln318_18_fu_2597_p2 = (or_ln318_17_fu_2591_p2 | icmp_ln318_10_fu_2581_p2);

assign or_ln318_19_fu_2793_p2 = (or_ln318_26_fu_2789_p2 | icmp_ln318_11_reg_4115);

assign or_ln318_1_fu_1137_p2 = (icmp_ln1494_1_fu_1065_p2 | and_ln318_1_fu_1131_p2);

assign or_ln318_20_fu_2983_p2 = (or_ln318_29_fu_2977_p2 | icmp_ln318_12_fu_2965_p2);

assign or_ln318_21_fu_3185_p2 = (or_ln318_32_fu_3179_p2 | icmp_ln318_13_fu_3169_p2);

assign or_ln318_22_fu_3383_p2 = (or_ln318_35_fu_3377_p2 | icmp_ln318_14_fu_3365_p2);

assign or_ln318_23_fu_3578_p2 = (or_ln318_38_fu_3572_p2 | icmp_ln318_15_fu_3560_p2);

assign or_ln318_24_fu_2677_p2 = (xor_ln318_2_fu_2671_p2 | and_ln318_11_fu_2575_p2);

assign or_ln318_25_fu_2683_p2 = (or_ln318_24_fu_2677_p2 | icmp_ln1494_11_fu_2560_p2);

assign or_ln318_26_fu_2789_p2 = (icmp_ln1496_3_reg_4120 | icmp_ln1494_12_reg_4099);

assign or_ln318_27_fu_2865_p2 = (xor_ln318_3_fu_2859_p2 | and_ln318_12_fu_2785_p2);

assign or_ln318_28_fu_2871_p2 = (or_ln318_27_fu_2865_p2 | icmp_ln1494_12_reg_4099);

assign or_ln318_29_fu_2977_p2 = (icmp_ln1496_4_fu_2971_p2 | icmp_ln1494_13_fu_2941_p2);

assign or_ln318_2_fu_1343_p2 = (icmp_ln1494_2_fu_1275_p2 | and_ln318_2_fu_1337_p2);

assign or_ln318_30_fu_3069_p2 = (xor_ln318_4_fu_3063_p2 | and_ln318_13_fu_2959_p2);

assign or_ln318_31_fu_3075_p2 = (or_ln318_30_fu_3069_p2 | icmp_ln1494_13_fu_2941_p2);

assign or_ln318_32_fu_3179_p2 = (icmp_ln1496_5_fu_3174_p2 | icmp_ln1494_14_fu_3148_p2);

assign or_ln318_33_fu_3264_p2 = (xor_ln318_5_fu_3258_p2 | and_ln318_14_fu_3163_p2);

assign or_ln318_34_fu_3270_p2 = (or_ln318_33_fu_3264_p2 | icmp_ln1494_14_fu_3148_p2);

assign or_ln318_35_fu_3377_p2 = (icmp_ln1496_6_fu_3371_p2 | icmp_ln1494_15_fu_3341_p2);

assign or_ln318_36_fu_3453_p2 = (xor_ln318_6_fu_3447_p2 | and_ln318_15_fu_3359_p2);

assign or_ln318_37_fu_3459_p2 = (or_ln318_36_fu_3453_p2 | icmp_ln1494_15_fu_3341_p2);

assign or_ln318_38_fu_3572_p2 = (icmp_ln1496_7_fu_3566_p2 | icmp_ln1494_16_fu_3536_p2);

assign or_ln318_39_fu_3600_p2 = (xor_ln318_7_fu_3594_p2 | and_ln318_16_fu_3554_p2);

assign or_ln318_3_fu_1473_p2 = (icmp_ln1494_3_fu_1401_p2 | and_ln318_3_fu_1467_p2);

assign or_ln318_40_fu_3606_p2 = (or_ln318_39_fu_3600_p2 | icmp_ln1494_16_fu_3536_p2);

assign or_ln318_4_fu_1597_p2 = (icmp_ln1494_4_fu_1529_p2 | and_ln318_4_fu_1591_p2);

assign or_ln318_5_fu_1727_p2 = (icmp_ln1494_5_fu_1655_p2 | and_ln318_5_fu_1721_p2);

assign or_ln318_6_fu_1851_p2 = (icmp_ln1494_6_fu_1783_p2 | and_ln318_6_fu_1845_p2);

assign or_ln318_7_fu_1971_p2 = (icmp_ln1494_7_fu_1909_p2 | and_ln318_7_fu_1965_p2);

assign or_ln318_8_fu_2091_p2 = (icmp_ln1494_8_fu_2022_p2 | and_ln318_8_fu_2039_p2);

assign or_ln318_9_fu_2207_p2 = (or_ln318_10_fu_2201_p2 | icmp_ln318_8_fu_2189_p2);

assign or_ln318_fu_990_p2 = (icmp_ln1494_fu_952_p2 | and_ln318_fu_985_p2);

assign or_ln331_1_fu_2427_p2 = (icmp_ln1495_9_fu_2409_p2 | and_ln331_1_fu_2421_p2);

assign or_ln331_2_fu_2624_p2 = (icmp_ln1495_10_fu_2608_p2 | and_ln331_2_fu_2618_p2);

assign or_ln331_3_fu_2815_p2 = (icmp_ln1495_11_fu_2802_p2 | and_ln331_3_fu_2810_p2);

assign or_ln331_4_fu_3013_p2 = (icmp_ln1495_12_fu_2995_p2 | and_ln331_4_fu_3007_p2);

assign or_ln331_5_fu_3212_p2 = (icmp_ln1495_13_fu_3196_p2 | and_ln331_5_fu_3206_p2);

assign or_ln331_6_fu_3407_p2 = (icmp_ln1495_14_fu_3389_p2 | and_ln331_6_fu_3401_p2);

assign or_ln331_fu_2258_p2 = (icmp_ln1495_8_fu_2245_p2 | and_ln331_fu_2253_p2);

assign p_Result_1_fu_3636_p3 = res_FH_l_V_fu_3624_p2[32'd17];

assign p_Result_25_1_fu_360_p4 = {{select_ln488_fu_344_p3[7:6]}};

assign p_Result_25_2_fu_442_p4 = {{select_ln488_2_fu_426_p3[7:5]}};

assign p_Result_25_3_fu_549_p4 = {{select_ln488_4_fu_537_p3[7:4]}};

assign p_Result_25_4_fu_631_p4 = {{select_ln488_6_fu_615_p3[7:3]}};

assign p_Result_25_5_fu_713_p4 = {{select_ln488_8_fu_697_p3[7:2]}};

assign p_Result_25_6_fu_788_p4 = {{select_ln488_10_fu_776_p3[7:1]}};

assign p_Result_28_1_fu_378_p4 = {{select_ln488_1_fu_352_p3[15:12]}};

assign p_Result_28_2_fu_460_p4 = {{select_ln488_3_fu_434_p3[14:10]}};

assign p_Result_28_3_fu_567_p4 = {{select_ln488_5_fu_543_p3[13:8]}};

assign p_Result_28_4_fu_649_p4 = {{select_ln488_7_fu_623_p3[12:6]}};

assign p_Result_28_5_fu_731_p4 = {{select_ln488_9_fu_705_p3[11:4]}};

assign p_Result_28_6_fu_806_p4 = {{select_ln488_11_fu_782_p3[10:2]}};

assign p_Result_30_1_fu_404_p5 = {{select_ln488_1_fu_352_p3[18:16]}, {sub_ln248_fu_398_p2}, {select_ln488_1_fu_352_p3[11:0]}};

assign p_Result_30_2_fu_518_p5 = {{select_ln488_3_reg_3698[18:15]}, {sub_ln248_1_reg_3710}, {select_ln488_3_reg_3698[9:0]}};

assign p_Result_30_3_fu_593_p5 = {{select_ln488_5_fu_543_p3[18:14]}, {sub_ln248_2_fu_587_p2}, {select_ln488_5_fu_543_p3[7:0]}};

assign p_Result_30_4_fu_675_p5 = {{select_ln488_7_fu_623_p3[18:13]}, {sub_ln248_3_fu_669_p2}, {select_ln488_7_fu_623_p3[5:0]}};

assign p_Result_30_5_fu_757_p5 = {{select_ln488_9_reg_3731[18:12]}, {sub_ln248_4_reg_3743}, {select_ln488_9_reg_3731[3:0]}};

assign p_Result_30_6_fu_832_p5 = {{select_ln488_11_fu_782_p3[18:11]}, {sub_ln248_5_fu_826_p2}, {select_ln488_11_fu_782_p3[1:0]}};

assign p_Result_30_7_fu_898_p5 = {{select_ln488_13_fu_862_p3[18:10]}, {sub_ln248_6_fu_892_p2}};

assign p_Result_34_1_fu_1019_p4 = {{select_ln318_fu_996_p3[16:15]}};

assign p_Result_34_3_fu_1371_p4 = {{select_ln318_6_fu_1349_p3[16:13]}};

assign p_Result_34_5_fu_1625_p4 = {{select_ln318_12_fu_1603_p3[16:11]}};

assign p_Result_34_7_fu_1879_p4 = {{select_ln318_18_fu_1857_p3[16:9]}};

assign p_Result_34_8_fu_2005_p4 = {{select_ln318_21_fu_1994_p3[16:8]}};

assign p_Result_s_77_fu_332_p5 = {{x_l_I_V_fu_298_p1[18:17]}, {add_ln248_fu_326_p2}, {x_l_I_V_fu_298_p1[13:0]}};

assign p_Result_s_fu_3465_p3 = x_V_read_reg_3682_pp0_iter11_reg[32'd31];

assign p_Val2_s_fu_3649_p3 = ((p_Result_1_fu_3636_p3[0:0] === 1'b1) ? res_I_V_fu_3644_p2 : select_ln488_14_reg_3768_pp0_iter11_reg);

assign p_neg_10_fu_2433_p3 = ((icmp_ln1496_1_fu_2387_p2[0:0] === 1'b1) ? 17'd131071 : 17'd0);

assign p_neg_11_fu_2630_p3 = ((icmp_ln1496_2_fu_2586_p2[0:0] === 1'b1) ? 17'd131071 : 17'd0);

assign p_neg_12_fu_2821_p3 = ((icmp_ln1496_3_reg_4120[0:0] === 1'b1) ? 17'd131071 : 17'd0);

assign p_neg_13_fu_3019_p3 = ((icmp_ln1496_4_fu_2971_p2[0:0] === 1'b1) ? 17'd131071 : 17'd0);

assign p_neg_14_fu_3218_p3 = ((icmp_ln1496_5_fu_3174_p2[0:0] === 1'b1) ? 17'd131071 : 17'd0);

assign p_neg_15_fu_3413_p3 = ((icmp_ln1496_6_fu_3371_p2[0:0] === 1'b1) ? 17'd131071 : 17'd0);

assign p_neg_9_fu_2264_p3 = ((icmp_ln1496_reg_4003[0:0] === 1'b1) ? 17'd131071 : 17'd0);

assign r_V_fu_3666_p3 = {{p_Val2_s_fu_3649_p3}, {tmp_35_fu_3656_p4}};

assign res_FH_V_fu_3630_p2 = (select_ln318_56_fu_3612_p3 + 17'd1);

assign res_FH_l_V_fu_3624_p2 = (zext_ln1192_fu_3620_p1 + 18'd1);

assign res_I_V_fu_3644_p2 = (select_ln488_14_reg_3768_pp0_iter11_reg + 8'd1);

assign select_ln318_10_fu_1487_p3 = ((or_ln318_3_fu_1473_p2[0:0] === 1'b1) ? sub_ln703_5_fu_1419_p2 : select_ln318_7_fu_1356_p3);

assign select_ln318_11_fu_1505_p3 = ((or_ln318_3_reg_3887[0:0] === 1'b1) ? sub_ln703_6_reg_3882 : select_ln318_8_reg_3877);

assign select_ln318_12_fu_1603_p3 = ((or_ln318_4_fu_1597_p2[0:0] === 1'b1) ? tmp_41_fu_1571_p4 : select_ln318_9_reg_3892);

assign select_ln318_13_fu_1610_p3 = ((or_ln318_4_fu_1597_p2[0:0] === 1'b1) ? sub_ln703_7_fu_1546_p2 : select_ln318_10_reg_3898);

assign select_ln318_14_fu_1617_p3 = ((or_ln318_4_fu_1597_p2[0:0] === 1'b1) ? sub_ln703_8_fu_1565_p2 : select_ln318_11_fu_1505_p3);

assign select_ln318_15_fu_1733_p3 = ((or_ln318_5_fu_1727_p2[0:0] === 1'b1) ? tmp_42_fu_1699_p4 : select_ln318_12_fu_1603_p3);

assign select_ln318_16_fu_1741_p3 = ((or_ln318_5_fu_1727_p2[0:0] === 1'b1) ? sub_ln703_9_fu_1673_p2 : select_ln318_13_fu_1610_p3);

assign select_ln318_17_fu_1759_p3 = ((or_ln318_5_reg_3921[0:0] === 1'b1) ? sub_ln703_10_reg_3916 : select_ln318_14_reg_3911);

assign select_ln318_18_fu_1857_p3 = ((or_ln318_6_fu_1851_p2[0:0] === 1'b1) ? tmp_43_fu_1825_p4 : select_ln318_15_reg_3926);

assign select_ln318_19_fu_1864_p3 = ((or_ln318_6_fu_1851_p2[0:0] === 1'b1) ? sub_ln703_11_fu_1800_p2 : select_ln318_16_reg_3932);

assign select_ln318_1_fu_1004_p3 = ((or_ln318_fu_990_p2[0:0] === 1'b1) ? add_ln703_24_fu_962_p2 : x_l_FH_V_fu_918_p3);

assign select_ln318_20_fu_1871_p3 = ((or_ln318_6_fu_1851_p2[0:0] === 1'b1) ? sub_ln703_12_fu_1819_p2 : select_ln318_17_fu_1759_p3);

assign select_ln318_21_fu_1994_p3 = ((or_ln318_7_reg_3961[0:0] === 1'b1) ? tmp_45_fu_1985_p4 : select_ln318_18_reg_3945);

assign select_ln318_22_fu_1977_p3 = ((or_ln318_7_fu_1971_p2[0:0] === 1'b1) ? sub_ln703_13_fu_1927_p2 : select_ln318_19_fu_1864_p3);

assign select_ln318_23_fu_2000_p3 = ((or_ln318_7_reg_3961[0:0] === 1'b1) ? sub_ln703_14_reg_3956 : select_ln318_20_reg_3951);

assign select_ln318_24_fu_2097_p3 = ((or_ln318_8_fu_2091_p2[0:0] === 1'b1) ? tmp_46_fu_2081_p4 : select_ln318_21_fu_1994_p3);

assign select_ln318_25_fu_2105_p3 = ((or_ln318_8_fu_2091_p2[0:0] === 1'b1) ? 17'd65536 : 17'd0);

assign select_ln318_26_fu_2113_p3 = ((or_ln318_8_fu_2091_p2[0:0] === 1'b1) ? add_ln703_8_fu_2062_p2 : select_ln318_22_reg_3967);

assign select_ln318_27_fu_2120_p3 = ((or_ln318_8_fu_2091_p2[0:0] === 1'b1) ? select_ln339_8_fu_2073_p3 : select_ln318_23_fu_2000_p3);

assign select_ln318_28_fu_2302_p3 = ((or_ln318_12_reg_4009[0:0] === 1'b1) ? tmp_47_fu_2293_p4 : select_ln318_24_reg_3975);

assign select_ln318_29_fu_2237_p3 = ((or_ln318_12_fu_2231_p2[0:0] === 1'b1) ? sub_ln703_15_fu_2213_p2 : select_ln318_25_fu_2105_p3);

assign select_ln318_2_fu_1012_p3 = ((or_ln318_fu_990_p2[0:0] === 1'b1) ? sub_ln703_fu_979_p2 : select_ln488_15_reg_3759);

assign select_ln318_30_fu_2308_p3 = ((or_ln318_12_reg_4009[0:0] === 1'b1) ? add_ln703_10_fu_2276_p2 : select_ln318_26_reg_3981);

assign select_ln318_31_fu_2314_p3 = ((or_ln318_12_reg_4009[0:0] === 1'b1) ? select_ln339_9_fu_2286_p3 : select_ln318_27_reg_3989);

assign select_ln318_32_fu_2517_p3 = ((or_ln318_16_reg_4029[0:0] === 1'b1) ? tmp_48_fu_2508_p4 : select_ln318_28_reg_4023);

assign select_ln318_33_fu_2485_p3 = ((or_ln318_16_fu_2479_p2[0:0] === 1'b1) ? sub_ln703_17_fu_2404_p2 : select_ln318_29_reg_4016);

assign select_ln318_34_fu_2492_p3 = ((or_ln318_16_fu_2479_p2[0:0] === 1'b1) ? add_ln703_12_fu_2447_p2 : select_ln318_30_fu_2308_p3);

assign select_ln318_35_fu_2500_p3 = ((or_ln318_16_fu_2479_p2[0:0] === 1'b1) ? select_ln339_10_fu_2459_p3 : select_ln318_31_fu_2314_p3);

assign select_ln318_36_fu_2689_p3 = ((or_ln318_25_fu_2683_p2[0:0] === 1'b1) ? tmp_49_fu_2661_p4 : select_ln318_32_fu_2517_p3);

assign select_ln318_37_fu_2697_p3 = ((or_ln318_25_fu_2683_p2[0:0] === 1'b1) ? sub_ln703_19_fu_2603_p2 : select_ln318_33_reg_4034);

assign select_ln318_38_fu_2704_p3 = ((or_ln318_25_fu_2683_p2[0:0] === 1'b1) ? add_ln703_14_fu_2644_p2 : select_ln318_34_reg_4041);

assign select_ln318_39_fu_2711_p3 = ((or_ln318_25_fu_2683_p2[0:0] === 1'b1) ? select_ln339_11_fu_2654_p3 : select_ln318_35_reg_4051);

assign select_ln318_3_fu_1143_p3 = ((or_ln318_1_fu_1137_p2[0:0] === 1'b1) ? tmp_38_fu_1109_p4 : select_ln318_fu_996_p3);

assign select_ln318_40_fu_2876_p3 = ((or_ln318_28_fu_2871_p2[0:0] === 1'b1) ? tmp_50_fu_2850_p4 : select_ln318_36_reg_4060);

assign select_ln318_41_fu_2883_p3 = ((or_ln318_28_fu_2871_p2[0:0] === 1'b1) ? sub_ln703_21_fu_2798_p2 : select_ln318_37_reg_4066);

assign select_ln318_42_fu_2890_p3 = ((or_ln318_28_fu_2871_p2[0:0] === 1'b1) ? add_ln703_16_fu_2833_p2 : select_ln318_38_reg_4072);

assign select_ln318_43_fu_2897_p3 = ((or_ln318_28_fu_2871_p2[0:0] === 1'b1) ? select_ln339_12_fu_2843_p3 : select_ln318_39_reg_4080);

assign select_ln318_44_fu_3081_p3 = ((or_ln318_31_fu_3075_p2[0:0] === 1'b1) ? tmp_51_fu_3053_p4 : select_ln318_40_fu_2876_p3);

assign select_ln318_45_fu_3089_p3 = ((or_ln318_31_fu_3075_p2[0:0] === 1'b1) ? sub_ln703_23_fu_2989_p2 : select_ln318_41_fu_2883_p3);

assign select_ln318_46_fu_3097_p3 = ((or_ln318_31_fu_3075_p2[0:0] === 1'b1) ? add_ln703_18_fu_3033_p2 : select_ln318_42_fu_2890_p3);

assign select_ln318_47_fu_3105_p3 = ((or_ln318_31_fu_3075_p2[0:0] === 1'b1) ? select_ln339_13_fu_3045_p3 : select_ln318_43_fu_2897_p3);

assign select_ln318_48_fu_3276_p3 = ((or_ln318_34_fu_3270_p2[0:0] === 1'b1) ? tmp_52_fu_3249_p4 : select_ln318_44_reg_4127);

assign select_ln318_49_fu_3283_p3 = ((or_ln318_34_fu_3270_p2[0:0] === 1'b1) ? sub_ln703_25_fu_3191_p2 : select_ln318_45_reg_4133);

assign select_ln318_4_fu_1151_p3 = ((or_ln318_1_fu_1137_p2[0:0] === 1'b1) ? sub_ln703_1_fu_1083_p2 : select_ln318_1_fu_1004_p3);

assign select_ln318_50_fu_3290_p3 = ((or_ln318_34_fu_3270_p2[0:0] === 1'b1) ? add_ln703_20_fu_3232_p2 : select_ln318_46_reg_4140);

assign select_ln318_51_fu_3297_p3 = ((or_ln318_34_fu_3270_p2[0:0] === 1'b1) ? select_ln339_14_fu_3242_p3 : select_ln318_47_reg_4150);

assign select_ln318_52_fu_3485_p3 = ((or_ln318_37_reg_4206[0:0] === 1'b1) ? tmp_53_fu_3476_p4 : select_ln318_48_reg_4169);

assign select_ln318_53_fu_3491_p3 = ((or_ln318_37_reg_4206[0:0] === 1'b1) ? sub_ln703_27_fu_3472_p2 : select_ln318_49_reg_4175);

assign select_ln318_54_fu_3497_p3 = ((or_ln318_37_reg_4206[0:0] === 1'b1) ? add_ln703_22_reg_4196 : select_ln318_50_reg_4181);

assign select_ln318_55_fu_3502_p3 = ((or_ln318_37_reg_4206[0:0] === 1'b1) ? select_ln339_15_reg_4201 : select_ln318_51_reg_4186);

assign select_ln318_56_fu_3612_p3 = ((or_ln318_40_fu_3606_p2[0:0] === 1'b1) ? tmp_55_fu_3584_p4 : select_ln318_52_fu_3485_p3);

assign select_ln318_5_fu_1251_p3 = ((or_ln318_1_reg_3793[0:0] === 1'b1) ? sub_ln703_2_reg_3788 : select_ln318_2_reg_3783);

assign select_ln318_6_fu_1349_p3 = ((or_ln318_2_fu_1343_p2[0:0] === 1'b1) ? tmp_39_fu_1317_p4 : select_ln318_3_reg_3798);

assign select_ln318_7_fu_1356_p3 = ((or_ln318_2_fu_1343_p2[0:0] === 1'b1) ? sub_ln703_3_fu_1292_p2 : select_ln318_4_reg_3804);

assign select_ln318_8_fu_1363_p3 = ((or_ln318_2_fu_1343_p2[0:0] === 1'b1) ? sub_ln703_4_fu_1311_p2 : select_ln318_5_fu_1251_p3);

assign select_ln318_9_fu_1479_p3 = ((or_ln318_3_fu_1473_p2[0:0] === 1'b1) ? tmp_40_fu_1445_p4 : select_ln318_6_fu_1349_p3);

assign select_ln318_fu_996_p3 = ((or_ln318_fu_990_p2[0:0] === 1'b1) ? 17'd65536 : 17'd0);

assign select_ln339_10_fu_2459_p3 = ((or_ln331_1_fu_2427_p2[0:0] === 1'b1) ? add_ln703_13_fu_2453_p2 : select_ln318_31_fu_2314_p3);

assign select_ln339_11_fu_2654_p3 = ((or_ln331_2_fu_2624_p2[0:0] === 1'b1) ? add_ln703_15_fu_2649_p2 : select_ln318_35_reg_4051);

assign select_ln339_12_fu_2843_p3 = ((or_ln331_3_fu_2815_p2[0:0] === 1'b1) ? add_ln703_17_fu_2838_p2 : select_ln318_39_reg_4080);

assign select_ln339_13_fu_3045_p3 = ((or_ln331_4_fu_3013_p2[0:0] === 1'b1) ? add_ln703_19_fu_3039_p2 : select_ln318_43_fu_2897_p3);

assign select_ln339_14_fu_3242_p3 = ((or_ln331_5_fu_3212_p2[0:0] === 1'b1) ? add_ln703_21_fu_3237_p2 : select_ln318_47_reg_4150);

assign select_ln339_15_fu_3439_p3 = ((or_ln331_6_fu_3407_p2[0:0] === 1'b1) ? add_ln703_23_fu_3433_p2 : select_ln318_51_fu_3297_p3);

assign select_ln339_1_fu_1095_p3 = ((icmp_ln1495_1_fu_1077_p2[0:0] === 1'b1) ? add_ln703_1_fu_1089_p2 : select_ln318_2_fu_1012_p3);

assign select_ln339_2_fu_1303_p3 = ((icmp_ln1495_2_fu_1287_p2[0:0] === 1'b1) ? add_ln703_2_fu_1297_p2 : select_ln318_5_fu_1251_p3);

assign select_ln339_3_fu_1431_p3 = ((icmp_ln1495_3_fu_1413_p2[0:0] === 1'b1) ? add_ln703_3_fu_1425_p2 : select_ln318_8_fu_1363_p3);

assign select_ln339_4_fu_1557_p3 = ((icmp_ln1495_4_fu_1541_p2[0:0] === 1'b1) ? add_ln703_4_fu_1551_p2 : select_ln318_11_fu_1505_p3);

assign select_ln339_5_fu_1685_p3 = ((icmp_ln1495_5_fu_1667_p2[0:0] === 1'b1) ? add_ln703_5_fu_1679_p2 : select_ln318_14_fu_1617_p3);

assign select_ln339_6_fu_1811_p3 = ((icmp_ln1495_6_fu_1795_p2[0:0] === 1'b1) ? add_ln703_6_fu_1805_p2 : select_ln318_17_fu_1759_p3);

assign select_ln339_7_fu_1939_p3 = ((icmp_ln1495_7_fu_1921_p2[0:0] === 1'b1) ? add_ln703_7_fu_1933_p2 : select_ln318_20_fu_1871_p3);

assign select_ln339_8_fu_2073_p3 = ((xor_ln331_fu_2050_p2[0:0] === 1'b1) ? add_ln703_9_fu_2067_p2 : select_ln318_23_fu_2000_p3);

assign select_ln339_9_fu_2286_p3 = ((or_ln331_fu_2258_p2[0:0] === 1'b1) ? add_ln703_11_fu_2281_p2 : select_ln318_27_reg_3989);

assign select_ln339_fu_973_p3 = ((icmp_ln1495_reg_3715_pp0_iter2_reg[0:0] === 1'b1) ? add_ln703_fu_968_p2 : select_ln488_15_reg_3759);

assign select_ln488_10_fu_776_p3 = ((icmp_ln488_5_reg_3737[0:0] === 1'b1) ? select_ln488_8_reg_3725 : tmp_24_fu_767_p4);

assign select_ln488_11_fu_782_p3 = ((icmp_ln488_5_reg_3737[0:0] === 1'b1) ? select_ln488_9_reg_3731 : p_Result_30_5_fu_757_p5);

assign select_ln488_12_fu_854_p3 = ((icmp_ln488_6_fu_820_p2[0:0] === 1'b1) ? select_ln488_10_fu_776_p3 : tmp_26_fu_844_p4);

assign select_ln488_13_fu_862_p3 = ((icmp_ln488_6_fu_820_p2[0:0] === 1'b1) ? select_ln488_11_fu_782_p3 : p_Result_30_6_fu_832_p5);

assign select_ln488_14_fu_934_p3 = ((icmp_ln488_7_reg_3754[0:0] === 1'b1) ? select_ln488_12_reg_3748 : tmp_27_fu_925_p4);

assign select_ln488_15_fu_910_p3 = ((icmp_ln488_7_fu_886_p2[0:0] === 1'b1) ? select_ln488_13_fu_862_p3 : p_Result_30_7_fu_898_p5);

assign select_ln488_1_fu_352_p3 = ((icmp_ln488_fu_320_p2[0:0] === 1'b1) ? x_l_I_V_fu_298_p1 : p_Result_s_77_fu_332_p5);

assign select_ln488_2_fu_426_p3 = ((icmp_ln488_1_fu_392_p2[0:0] === 1'b1) ? select_ln488_fu_344_p3 : tmp_16_fu_416_p4);

assign select_ln488_3_fu_434_p3 = ((icmp_ln488_1_fu_392_p2[0:0] === 1'b1) ? select_ln488_1_fu_352_p3 : p_Result_30_1_fu_404_p5);

assign select_ln488_4_fu_537_p3 = ((icmp_ln488_2_reg_3704[0:0] === 1'b1) ? select_ln488_2_reg_3692 : tmp_18_fu_528_p4);

assign select_ln488_5_fu_543_p3 = ((icmp_ln488_2_reg_3704[0:0] === 1'b1) ? select_ln488_3_reg_3698 : p_Result_30_2_fu_518_p5);

assign select_ln488_6_fu_615_p3 = ((icmp_ln488_3_fu_581_p2[0:0] === 1'b1) ? select_ln488_4_fu_537_p3 : tmp_20_fu_605_p4);

assign select_ln488_7_fu_623_p3 = ((icmp_ln488_3_fu_581_p2[0:0] === 1'b1) ? select_ln488_5_fu_543_p3 : p_Result_30_3_fu_593_p5);

assign select_ln488_8_fu_697_p3 = ((icmp_ln488_4_fu_663_p2[0:0] === 1'b1) ? select_ln488_6_fu_615_p3 : tmp_22_fu_687_p4);

assign select_ln488_9_fu_705_p3 = ((icmp_ln488_4_fu_663_p2[0:0] === 1'b1) ? select_ln488_7_fu_623_p3 : p_Result_30_4_fu_675_p5);

assign select_ln488_fu_344_p3 = ((icmp_ln488_fu_320_p2[0:0] === 1'b1) ? 8'd0 : 8'd128);

assign sub_ln248_1_fu_480_p2 = (p_Result_28_2_fu_460_p4 - zext_ln488_1_fu_470_p1);

assign sub_ln248_2_fu_587_p2 = (p_Result_28_3_fu_567_p4 - zext_ln488_2_fu_577_p1);

assign sub_ln248_3_fu_669_p2 = (p_Result_28_4_fu_649_p4 - zext_ln488_3_fu_659_p1);

assign sub_ln248_4_fu_751_p2 = (p_Result_28_5_fu_731_p4 - zext_ln488_4_fu_741_p1);

assign sub_ln248_5_fu_826_p2 = (p_Result_28_6_fu_806_p4 - zext_ln488_5_fu_816_p1);

assign sub_ln248_6_fu_892_p2 = (trunc_ln612_fu_878_p1 - zext_ln488_6_fu_882_p1);

assign sub_ln248_fu_398_p2 = (p_Result_28_1_fu_378_p4 - zext_ln488_fu_388_p1);

assign sub_ln703_10_fu_1693_p2 = (select_ln339_5_fu_1685_p3 - zext_ln1494_5_fu_1651_p1);

assign sub_ln703_11_fu_1800_p2 = (select_ln318_16_reg_3932 - trunc_ln708_12_fu_1771_p4);

assign sub_ln703_12_fu_1819_p2 = (select_ln339_6_fu_1811_p3 - zext_ln1494_6_fu_1779_p1);

assign sub_ln703_13_fu_1927_p2 = (select_ln318_19_fu_1864_p3 - trunc_ln708_14_fu_1896_p4);

assign sub_ln703_14_fu_1947_p2 = (select_ln339_7_fu_1939_p3 - zext_ln1494_7_fu_1905_p1);

assign sub_ln703_15_fu_2213_p2 = (select_ln318_25_fu_2105_p3 - mul_FL_V_9_fu_2157_p3);

assign sub_ln703_16_fu_2271_p2 = (p_neg_9_fu_2264_p3 - trunc_ln708_16_reg_3996);

assign sub_ln703_17_fu_2404_p2 = (select_ln318_29_reg_4016 - mul_FL_V_s_fu_2349_p3);

assign sub_ln703_18_fu_2441_p2 = (p_neg_10_fu_2433_p3 - trunc_ln708_17_fu_2340_p4);

assign sub_ln703_19_fu_2603_p2 = (select_ln318_33_reg_4034 - mul_FL_V_1_fu_2552_p3);

assign sub_ln703_1_fu_1083_p2 = (select_ln318_1_fu_1004_p3 - trunc_ln708_4_fu_1051_p4);

assign sub_ln703_20_fu_2638_p2 = (p_neg_11_fu_2630_p3 - trunc_ln708_18_fu_2543_p4);

assign sub_ln703_21_fu_2798_p2 = (select_ln318_37_reg_4066 - mul_FL_V_2_reg_4094);

assign sub_ln703_22_fu_2828_p2 = (p_neg_12_fu_2821_p3 - trunc_ln708_19_reg_4087);

assign sub_ln703_23_fu_2989_p2 = (select_ln318_41_fu_2883_p3 - mul_FL_V_3_fu_2933_p3);

assign sub_ln703_24_fu_3027_p2 = (p_neg_13_fu_3019_p3 - trunc_ln708_20_fu_2924_p4);

assign sub_ln703_25_fu_3191_p2 = (select_ln318_45_reg_4133 - mul_FL_V_4_fu_3141_p3);

assign sub_ln703_26_fu_3226_p2 = (p_neg_14_fu_3218_p3 - trunc_ln708_21_fu_3133_p4);

assign sub_ln703_27_fu_3472_p2 = (select_ln318_49_reg_4175 - mul_FL_V_5_reg_4191);

assign sub_ln703_28_fu_3421_p2 = (p_neg_15_fu_3413_p3 - trunc_ln708_22_fu_3324_p4);

assign sub_ln703_2_fu_1103_p2 = (select_ln339_1_fu_1095_p3 - zext_ln1494_1_fu_1061_p1);

assign sub_ln703_3_fu_1292_p2 = (select_ln318_4_reg_3804 - trunc_ln708_6_fu_1263_p4);

assign sub_ln703_4_fu_1311_p2 = (select_ln339_2_fu_1303_p3 - zext_ln1494_2_fu_1271_p1);

assign sub_ln703_5_fu_1419_p2 = (select_ln318_7_fu_1356_p3 - trunc_ln708_8_fu_1388_p4);

assign sub_ln703_6_fu_1439_p2 = (select_ln339_3_fu_1431_p3 - zext_ln1494_3_fu_1397_p1);

assign sub_ln703_7_fu_1546_p2 = (select_ln318_10_reg_3898 - trunc_ln708_s_fu_1517_p4);

assign sub_ln703_8_fu_1565_p2 = (select_ln339_4_fu_1557_p3 - zext_ln1494_4_fu_1525_p1);

assign sub_ln703_9_fu_1673_p2 = (select_ln318_13_fu_1610_p3 - trunc_ln708_10_fu_1642_p4);

assign sub_ln703_fu_979_p2 = (select_ln339_fu_973_p3 - zext_ln1494_fu_948_p1);

assign tmp_10_fu_2718_p4 = {{select_ln318_36_fu_2689_p3[11:4]}};

assign tmp_11_fu_2904_p4 = {{select_ln318_40_fu_2876_p3[12:3]}};

assign tmp_13_fu_3304_p4 = {{select_ln318_48_fu_3276_p3[14:1]}};

assign tmp_14_fu_1029_p4 = {{select_ln488_14_fu_934_p3[7:1]}};

always @ (*) begin
    tmp_16_fu_416_p4 = select_ln488_fu_344_p3;
    tmp_16_fu_416_p4[32'd6] = |(1'd1);
end

always @ (*) begin
    tmp_18_fu_528_p4 = select_ln488_2_reg_3692;
    tmp_18_fu_528_p4[32'd5] = |(1'd1);
end

assign tmp_1_fu_370_p3 = {{p_Result_25_1_fu_360_p4}, {1'd1}};

always @ (*) begin
    tmp_20_fu_605_p4 = select_ln488_4_fu_537_p3;
    tmp_20_fu_605_p4[32'd4] = |(1'd1);
end

always @ (*) begin
    tmp_22_fu_687_p4 = select_ln488_6_fu_615_p3;
    tmp_22_fu_687_p4[32'd3] = |(1'd1);
end

always @ (*) begin
    tmp_24_fu_767_p4 = select_ln488_8_reg_3725;
    tmp_24_fu_767_p4[32'd2] = |(1'd1);
end

assign tmp_25_fu_2138_p4 = {{select_ln318_24_fu_2097_p3[16:9]}};

always @ (*) begin
    tmp_26_fu_844_p4 = select_ln488_10_fu_776_p3;
    tmp_26_fu_844_p4[32'd1] = |(1'd1);
end

always @ (*) begin
    tmp_27_fu_925_p4 = select_ln488_12_reg_3748;
    tmp_27_fu_925_p4[32'd0] = |(1'd1);
end

assign tmp_28_fu_486_p4 = {{x_V_int_reg[15:14]}};

assign tmp_29_fu_2330_p4 = {{select_ln318_28_fu_2302_p3[16:10]}};

assign tmp_2_fu_452_p3 = {{p_Result_25_2_fu_442_p4}, {1'd1}};

assign tmp_30_fu_2533_p4 = {{select_ln318_32_fu_2517_p3[16:11]}};

assign tmp_31_fu_2728_p4 = {{select_ln318_36_fu_2689_p3[16:12]}};

assign tmp_32_fu_2914_p4 = {{select_ln318_40_fu_2876_p3[16:13]}};

assign tmp_34_fu_3314_p4 = {{select_ln318_48_fu_3276_p3[16:15]}};

assign tmp_35_fu_3656_p4 = {{res_FH_V_fu_3630_p2[16:1]}};

assign tmp_36_fu_502_p4 = {{x_V_int_reg[15:14]}};

always @ (*) begin
    tmp_38_fu_1109_p4 = select_ln318_fu_996_p3;
    tmp_38_fu_1109_p4[32'd15] = |(1'd1);
end

always @ (*) begin
    tmp_39_fu_1317_p4 = select_ln318_3_reg_3798;
    tmp_39_fu_1317_p4[32'd14] = |(1'd1);
end

assign tmp_3_fu_559_p3 = {{p_Result_25_3_fu_549_p4}, {1'd1}};

always @ (*) begin
    tmp_40_fu_1445_p4 = select_ln318_6_fu_1349_p3;
    tmp_40_fu_1445_p4[32'd13] = |(1'd1);
end

always @ (*) begin
    tmp_41_fu_1571_p4 = select_ln318_9_reg_3892;
    tmp_41_fu_1571_p4[32'd12] = |(1'd1);
end

always @ (*) begin
    tmp_42_fu_1699_p4 = select_ln318_12_fu_1603_p3;
    tmp_42_fu_1699_p4[32'd11] = |(1'd1);
end

always @ (*) begin
    tmp_43_fu_1825_p4 = select_ln318_15_reg_3926;
    tmp_43_fu_1825_p4[32'd10] = |(1'd1);
end

always @ (*) begin
    tmp_45_fu_1985_p4 = select_ln318_18_reg_3945;
    tmp_45_fu_1985_p4[32'd9] = |(1'd1);
end

always @ (*) begin
    tmp_46_fu_2081_p4 = select_ln318_21_fu_1994_p3;
    tmp_46_fu_2081_p4[32'd8] = |(1'd1);
end

always @ (*) begin
    tmp_47_fu_2293_p4 = select_ln318_24_reg_3975;
    tmp_47_fu_2293_p4[32'd7] = |(1'd1);
end

always @ (*) begin
    tmp_48_fu_2508_p4 = select_ln318_28_reg_4023;
    tmp_48_fu_2508_p4[32'd6] = |(1'd1);
end

always @ (*) begin
    tmp_49_fu_2661_p4 = select_ln318_32_fu_2517_p3;
    tmp_49_fu_2661_p4[32'd5] = |(1'd1);
end

assign tmp_4_fu_641_p3 = {{p_Result_25_4_fu_631_p4}, {1'd1}};

always @ (*) begin
    tmp_50_fu_2850_p4 = select_ln318_36_reg_4060;
    tmp_50_fu_2850_p4[32'd4] = |(1'd1);
end

always @ (*) begin
    tmp_51_fu_3053_p4 = select_ln318_40_fu_2876_p3;
    tmp_51_fu_3053_p4[32'd3] = |(1'd1);
end

always @ (*) begin
    tmp_52_fu_3249_p4 = select_ln318_44_reg_4127;
    tmp_52_fu_3249_p4[32'd2] = |(1'd1);
end

always @ (*) begin
    tmp_53_fu_3476_p4 = select_ln318_48_reg_4169;
    tmp_53_fu_3476_p4[32'd1] = |(1'd1);
end

assign tmp_54_fu_3519_p3 = select_ln318_52_fu_3485_p3[32'd16];

always @ (*) begin
    tmp_55_fu_3584_p4 = select_ln318_52_fu_3485_p3;
    tmp_55_fu_3584_p4[32'd0] = |(1'd1);
end

assign tmp_5_fu_723_p3 = {{p_Result_25_5_fu_713_p4}, {1'd1}};

assign tmp_6_fu_798_p3 = {{p_Result_25_6_fu_788_p4}, {1'd1}};

assign tmp_7_fu_870_p3 = {{select_ln488_12_fu_854_p3}, {1'd1}};

assign tmp_8_fu_2128_p4 = {{select_ln318_24_fu_2097_p3[8:7]}};

assign tmp_9_fu_2320_p4 = {{select_ln318_28_fu_2302_p3[9:6]}};

assign tmp_fu_306_p4 = {{x_V_int_reg[31:30]}};

assign tmp_s_fu_2523_p4 = {{select_ln318_32_fu_2517_p3[10:5]}};

assign trunc_ln103_fu_3507_p1 = select_ln318_52_fu_3485_p3[15:0];

assign trunc_ln612_fu_878_p1 = select_ln488_13_fu_862_p3[9:0];

assign trunc_ln708_10_fu_1642_p4 = {{{trunc_ln708_27_reg_3852_pp0_iter4_reg}, {p_Result_34_5_fu_1625_p4}}, {6'd32}};

assign trunc_ln708_11_fu_1764_p3 = {{15'd0}, {tmp_23_reg_3857_pp0_iter5_reg}};

assign trunc_ln708_12_fu_1771_p4 = {{{trunc_ln708_28_reg_3862_pp0_iter5_reg}, {p_Result_34_6_reg_3940}}, {4'd8}};

assign trunc_ln708_13_fu_1889_p3 = {{16'd0}, {tmp_44_reg_3867_pp0_iter5_reg}};

assign trunc_ln708_14_fu_1896_p4 = {{{trunc_ln708_29_reg_3872_pp0_iter5_reg}, {p_Result_34_7_fu_1879_p4}}, {2'd2}};

assign trunc_ln708_15_fu_2015_p3 = {{select_ln488_14_reg_3768_pp0_iter6_reg}, {p_Result_34_8_fu_2005_p4}};

assign trunc_ln708_16_fu_2148_p4 = {{{{1'd0}, {select_ln488_14_reg_3768_pp0_iter6_reg}}}, {tmp_25_fu_2138_p4}};

assign trunc_ln708_17_fu_2340_p4 = {{{{2'd0}, {select_ln488_14_reg_3768_pp0_iter7_reg}}}, {tmp_29_fu_2330_p4}};

assign trunc_ln708_18_fu_2543_p4 = {{{{3'd0}, {select_ln488_14_reg_3768_pp0_iter8_reg}}}, {tmp_30_fu_2533_p4}};

assign trunc_ln708_19_fu_2738_p4 = {{{{4'd0}, {select_ln488_14_reg_3768_pp0_iter8_reg}}}, {tmp_31_fu_2728_p4}};

assign trunc_ln708_1_fu_940_p3 = {{9'd0}, {select_ln488_14_fu_934_p3}};

assign trunc_ln708_20_fu_2924_p4 = {{{{5'd0}, {select_ln488_14_reg_3768_pp0_iter9_reg}}}, {tmp_32_fu_2914_p4}};

assign trunc_ln708_21_fu_3133_p4 = {{{{6'd0}, {select_ln488_14_reg_3768_pp0_iter10_reg}}}, {tmp_33_reg_4164}};

assign trunc_ln708_22_fu_3324_p4 = {{{{7'd0}, {select_ln488_14_reg_3768_pp0_iter10_reg}}}, {tmp_34_fu_3314_p4}};

assign trunc_ln708_23_fu_3527_p4 = {{{{8'd0}, {select_ln488_14_reg_3768_pp0_iter11_reg}}}, {tmp_54_fu_3519_p3}};

assign trunc_ln708_24_fu_1179_p1 = select_ln488_14_fu_934_p3[1:0];

assign trunc_ln708_25_fu_1193_p1 = select_ln488_14_fu_934_p3[2:0];

assign trunc_ln708_26_fu_1207_p1 = select_ln488_14_fu_934_p3[3:0];

assign trunc_ln708_27_fu_1221_p1 = select_ln488_14_fu_934_p3[4:0];

assign trunc_ln708_28_fu_1235_p1 = select_ln488_14_fu_934_p3[5:0];

assign trunc_ln708_29_fu_1247_p1 = select_ln488_14_fu_934_p3[6:0];

assign trunc_ln708_2_fu_1635_p3 = {{14'd0}, {tmp_21_reg_3847_pp0_iter4_reg}};

assign trunc_ln708_3_fu_1039_p3 = {{10'd0}, {tmp_14_fu_1029_p4}};

assign trunc_ln708_4_fu_1051_p4 = {{{trunc_ln708_fu_1047_p1}, {p_Result_34_1_fu_1019_p4}}, {14'd8192}};

assign trunc_ln708_5_fu_1256_p3 = {{11'd0}, {tmp_15_reg_3817}};

assign trunc_ln708_6_fu_1263_p4 = {{{trunc_ln708_24_reg_3822}, {p_Result_34_2_reg_3812}}, {12'd2048}};

assign trunc_ln708_7_fu_1381_p3 = {{12'd0}, {tmp_17_reg_3827}};

assign trunc_ln708_8_fu_1388_p4 = {{{trunc_ln708_25_reg_3832}, {p_Result_34_3_fu_1371_p4}}, {10'd512}};

assign trunc_ln708_9_fu_1510_p3 = {{13'd0}, {tmp_19_reg_3837_pp0_iter4_reg}};

assign trunc_ln708_fu_1047_p1 = select_ln488_14_fu_934_p3[0:0];

assign trunc_ln708_s_fu_1517_p4 = {{{trunc_ln708_26_reg_3842_pp0_iter4_reg}, {p_Result_34_4_reg_3906}}, {8'd128}};

assign trunc_ln731_fu_302_p1 = x_V_int_reg[15:0];

assign trunc_ln_fu_288_p4 = {{x_V_int_reg[31:16]}};

assign x_l_FH_V_fu_918_p3 = {{trunc_ln731_reg_3687_pp0_iter2_reg}, {1'd0}};

assign x_l_I_V_fu_298_p1 = trunc_ln_fu_288_p4;

assign xor_ln318_10_fu_1461_p2 = (icmp_ln318_3_fu_1455_p2 ^ 1'd1);

assign xor_ln318_11_fu_1585_p2 = (icmp_ln318_4_fu_1580_p2 ^ 1'd1);

assign xor_ln318_12_fu_1715_p2 = (icmp_ln318_5_fu_1709_p2 ^ 1'd1);

assign xor_ln318_13_fu_1839_p2 = (icmp_ln318_6_fu_1834_p2 ^ 1'd1);

assign xor_ln318_14_fu_1959_p2 = (icmp_ln318_7_fu_1953_p2 ^ 1'd1);

assign xor_ln318_1_fu_2467_p2 = (or_ln318_14_fu_2398_p2 ^ 1'd1);

assign xor_ln318_2_fu_2671_p2 = (or_ln318_18_fu_2597_p2 ^ 1'd1);

assign xor_ln318_3_fu_2859_p2 = (or_ln318_19_fu_2793_p2 ^ 1'd1);

assign xor_ln318_4_fu_3063_p2 = (or_ln318_20_fu_2983_p2 ^ 1'd1);

assign xor_ln318_5_fu_3258_p2 = (or_ln318_21_fu_3185_p2 ^ 1'd1);

assign xor_ln318_6_fu_3447_p2 = (or_ln318_22_fu_3383_p2 ^ 1'd1);

assign xor_ln318_7_fu_3594_p2 = (or_ln318_23_fu_3578_p2 ^ 1'd1);

assign xor_ln318_8_fu_1125_p2 = (icmp_ln318_1_fu_1119_p2 ^ 1'd1);

assign xor_ln318_9_fu_1331_p2 = (icmp_ln318_2_fu_1326_p2 ^ 1'd1);

assign xor_ln318_fu_2219_p2 = (or_ln318_9_fu_2207_p2 ^ 1'd1);

assign xor_ln331_fu_2050_p2 = (icmp_ln331_fu_2045_p2 ^ 1'd1);

assign xor_ln703_fu_2056_p2 = (trunc_ln708_15_fu_2015_p3 ^ 17'd131071);

assign zext_ln1192_fu_3620_p1 = select_ln318_56_fu_3612_p3;

assign zext_ln1494_1_fu_1061_p1 = trunc_ln708_3_fu_1039_p3;

assign zext_ln1494_2_fu_1271_p1 = trunc_ln708_5_fu_1256_p3;

assign zext_ln1494_3_fu_1397_p1 = trunc_ln708_7_fu_1381_p3;

assign zext_ln1494_4_fu_1525_p1 = trunc_ln708_9_fu_1510_p3;

assign zext_ln1494_5_fu_1651_p1 = trunc_ln708_2_fu_1635_p3;

assign zext_ln1494_6_fu_1779_p1 = trunc_ln708_11_fu_1764_p3;

assign zext_ln1494_7_fu_1905_p1 = trunc_ln708_13_fu_1889_p3;

assign zext_ln1494_fu_948_p1 = trunc_ln708_1_fu_940_p3;

assign zext_ln248_fu_316_p1 = tmp_fu_306_p4;

assign zext_ln488_1_fu_470_p1 = tmp_2_fu_452_p3;

assign zext_ln488_2_fu_577_p1 = tmp_3_fu_559_p3;

assign zext_ln488_3_fu_659_p1 = tmp_4_fu_641_p3;

assign zext_ln488_4_fu_741_p1 = tmp_5_fu_723_p3;

assign zext_ln488_5_fu_816_p1 = tmp_6_fu_798_p3;

assign zext_ln488_6_fu_882_p1 = tmp_7_fu_870_p3;

assign zext_ln488_fu_388_p1 = tmp_1_fu_370_p3;

always @ (posedge ap_clk) begin
    select_ln318_4_reg_3804[0] <= 1'b0;
    select_ln318_10_reg_3898[0] <= 1'b0;
    select_ln318_16_reg_3932[0] <= 1'b0;
    select_ln318_22_reg_3967[0] <= 1'b0;
    trunc_ln708_16_reg_3996[16] <= 1'b0;
    select_ln318_29_reg_4016[13:0] <= 14'b00000000000000;
    select_ln318_33_reg_4034[11:0] <= 12'b000000000000;
    select_ln318_37_reg_4066[9:0] <= 10'b0000000000;
    trunc_ln708_19_reg_4087[16:13] <= 4'b0000;
    mul_FL_V_2_reg_4094[8:0] <= 9'b100000000;
    select_ln318_45_reg_4133[5:0] <= 6'b000000;
    select_ln318_49_reg_4175[3:0] <= 4'b0000;
    mul_FL_V_5_reg_4191[2:0] <= 3'b100;
end

endmodule //monte_sim_dev_sqrt_fixed_32_16_s
