# This file automatically generated by vpl
# please do not modify
set local_dir ".local"
source -notrace "$local_dir/ocl_util.tcl"
source -notrace "$local_dir/platform.tcl"
source -notrace "$local_dir/debug_profile.tcl"
source -notrace "$local_dir/debug_profile_util.tcl"
source -notrace "$local_dir/debug_hw.tcl"
source -notrace "$local_dir/profile_hw.tcl"
source -notrace "$local_dir/profile_hwemu.tcl"
source -notrace "$local_dir/debug_profile_automation.tcl"
source -notrace "$local_dir/hw_emu_common_util.tcl"

# Remove the dummy proc in the ocl_util.tcl file
if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
  rename ::OPTRACE ""
}
set optraceCount 0

proc ::OPTRACE { action task {tags ""} } {
    global optraceCount
    set optraceCount [expr "$optraceCount" + 1]
    set scriptFileName "ipirun.tcl"
    set catagory "sdx_vpl"
    set timeStamp [clock milliseconds]

    puts "\[OPTRACE\]|[pid]|$optraceCount|$scriptFileName|$catagory|$timeStamp|$action|$task|$tags"
}
OPTRACE "START" "ipirun" "ROLLUP_0"
set vivado_error_file "vivado_error.txt"
set vivado_warn_file "vivado_warning.txt"
set output_dir "output"
set input_dir "input"
set steps_log "../../link.steps.log"
set kernel_ip_dirs {
  {/home/centos/src/project_data/aws-fpga/Vitis/examples/xilinx_2019.2/cpp_kernels/monte_sim/build_dir.hw_emu.xilinx_aws-vu9p-f1_shell-v04261818_201920_1/link/int/xo/ip_repo/xilinx_com_hls_monte_sim_dev_1_0}
  {/home/centos/src/project_data/aws-fpga/Vitis/examples/xilinx_2019.2/cpp_kernels/monte_sim/build_dir.hw_emu.xilinx_aws-vu9p-f1_shell-v04261818_201920_1/link/int/xo/ip_repo/xilinx_com_hls_monte_sim_1_0}}
set install_ip_cache "/opt/Xilinx/Vitis/2019.2/data/cache/xilinx"

set dict_slr_floorplan_parent_assignment [dict create \
  file_path ".local/hw_platform/tcl_hooks/slr_floorplan_parent_assignment.xdc" \
  used_in "implementation" \
  processing_order "LATE" \
];

set impl_xdc [dict create \
  slr_floorplan_parent_assignment ${dict_slr_floorplan_parent_assignment} \
];

set dict_slr_floorplan [dict create \
  file_path ".local/hw_platform/tcl_hooks/slr_floorplan.xdc" \
  used_in "implementation" \
  processing_order "NORMAL" \
];
set dict_cl_synth_aws [dict create \
  file_path ".local/hw_platform/tcl_hooks/cl_synth_aws.xdc" \
  used_in "synthesis implementation" \
  processing_order "LATE" \
];
set dict_cl_clocks_aws [dict create \
  file_path ".local/hw_platform/tcl_hooks/cl_clocks_aws.xdc" \
  used_in "out_of_context synthesis implementation" \
  processing_order "EARLY" \
];
set dict_cl_ddr [dict create \
  file_path ".local/hw_platform/tcl_hooks/cl_ddr.xdc" \
  used_in "synthesis implementation" \
  processing_order "LATE" \
];

set synth_xdc [dict create \
  slr_floorplan ${dict_slr_floorplan} \
  cl_synth_aws ${dict_cl_synth_aws} \
  cl_clocks_aws ${dict_cl_clocks_aws} \
  cl_ddr ${dict_cl_ddr} \
];

set utilization [dict create \
  luts                   -1 \
  brams                  -1 \
  registers              -1 \
  dsps                   -1 \
];


set bus_sp_tags [list]
set bus_sp_indeces [list]

lappend bus_sp_tags M00_AXI_MEM00 DDR
lappend bus_sp_indeces M00_AXI_MEM00 0
lappend bus_sp_tags M01_AXI_MEM00 DDR
lappend bus_sp_indeces M01_AXI_MEM00 1
lappend bus_sp_tags M02_AXI_MEM00 DDR
lappend bus_sp_indeces M02_AXI_MEM00 2
lappend bus_sp_tags M03_AXI_MEM00 DDR
lappend bus_sp_indeces M03_AXI_MEM00 3
lappend bus_sp_tags PLRAM_MEM00 PLRAM
lappend bus_sp_indeces PLRAM_MEM00 0
lappend bus_sp_tags PLRAM_MEM01 PLRAM
lappend bus_sp_indeces PLRAM_MEM01 1
lappend bus_sp_tags PLRAM_MEM02 PLRAM
lappend bus_sp_indeces PLRAM_MEM02 2

set hw_platform_info [dict create \
  hw_platform_dir              ".local/hw_platform" \
  hw_platform_part             "xcvu9p-flgb2104-2-i" \
  hw_platform_vbnv             "xilinx:aws-vu9p-f1:shell-v04261818:201920.1" \
  bb_locked_dcp                ".local/hw_platform/xilinx_aws-vu9p-f1_shell-v04261818_201920_1_bb_locked.dcp" \
  hw_platform_uses_pr           true \
  uses_pr_shell_dcp             false \
  pr_shell_dcp                 "" \
  hw_platform_state            "impl" \
  ocl_region                   "WRAPPER_INST/CL" \
  dr_bd_name                   "cl.bd" \
  utilization                   $utilization \
  hw_platform_dr_bd            ".local/hw_platform/emu/pfm_dynamic/pfm_dynamic.bd" \
  hw_platform_rebuild_tcl      "" \
  pre_sys_link_tcl             ".local/hw_platform/emu/dynamic_pre_sys_link.tcl" \
  post_sys_link_tcl            ".local/hw_platform/emu/dynamic_post_sys_link.tcl" \
  user_pre_sys_link_tcl        "" \
  user_post_sys_link_tcl       "" \
  synth_xdc                     $synth_xdc \
  impl_xdc                      $impl_xdc \
  hw_platform_ip_repo          ".local/hw_platform/iprepo" \
  hw_platform_ip_cache         ".local/hw_platform/ipcache" \
  emu_user_ip_repo             ".local/hw_platform/emu/user_ip_repo" \
  emu_src_dir                  "" \
  hw_platform_board_repo       "" \
  hw_platform_bconn_locked      {} \
  hw_platform_bconn_unlocked    {} \
  hw_platform_board_part       "" \
  link_output_format           "dcp" \
  is_unified                    true \
  xpfm_file                    "/home/centos/src/project_data/aws-fpga/Vitis/aws_platform/xilinx_aws-vu9p-f1_shell-v04261818_201920_1/xilinx_aws-vu9p-f1_shell-v04261818_201920_1.xpfm" \
  bus_sp_tags                   $bus_sp_tags \
  bus_sp_indeces                $bus_sp_indeces\
  design_intent_server_managed  true \
  design_intent_external_host   true \
  design_intent_datacenter      true \
  design_intent_embedded        false \
];


set config_info [dict create \
  proj_name                "prj" \
  emu_proj_name            "prj" \
  design_name              "dr" \
  out_partial_bitstream    "$output_dir/partial.bit" \
  out_partial_pdi          "$output_dir/partial.pdi" \
  out_partial_clear_bit    "$output_dir/partial_clear.bit" \
  out_full_bitstream       "$output_dir/system.bit" \
  out_full_pdi             "$output_dir/system.pdi" \
  enable_dont_partition     true \
  enable_util_report        true \
  utilization_threshold     0.8 \
  generate_script_only      false \
  run_script_map_file      "" \
  clbinary_name            "monte_sim" \
  kernels                  "monte_sim monte_sim_dev" \
  steps_log                 $steps_log \
  impl_from_step           "" \
  impl_to_step             "" \
  num_jobs                  2 \
  lsf_string               {} \
  optimize_level            0 \
  is_hw_emu                 true \
  user_ip_repo              {} \
  kernel_ip_dirs            $kernel_ip_dirs \
  no_hw_platform_ip_cache   false \
  no_install_ip_cache       false \
  install_ip_cache          $install_ip_cache \
  no_ip_cache               false \
  remote_ip_cache          "" \
  user_board_repo           {} \
  user_bconn                {} \
  dr_bd_tcl                ".local/dr.bd.tcl" \
  webtalk_flag             "Vitis" \
  encrypt_impl_dcp          false \
  encrypt_key_file         "" \
  enable_pr_verify          false \
  return_pre_sys_link_tcl   false \
  return_pre_synth          false \
  return_post_synth         false \
  return_pre_impl           false \
  disable_run_configs       false \
  protocol_checker          false \
  hw_emu_profiling          true \
  scripts_dir              "scripts" \
  output_dir               "$output_dir" \
  input_dir                "$input_dir" \
  local_dir                "$local_dir" \
  tclhook_prefix           "_vpl" \
  partition_def            "my_pd" \
  reconfig_module          "my_rm" \
  failfast_config          {} \
  enable_explicit_emu_data  false \
  aie_archive_file         "/home/centos/src/project_data/aws-fpga/Vitis/examples/xilinx_2019.2/cpp_kernels/monte_sim/build_dir.hw_emu.xilinx_aws-vu9p-f1_shell-v04261818_201920_1/link/int/system.aieprj" \
  system_dpa_enabled       "1" \
  is_hw_export             "false" \
  fixed_xsa                "vpl_gen_fixed.xsa" \
];

# kernel clock 'PL 1' (1)
set dict_kernel2_clk_clk [dict create \
  is_user_set false \
  clk_id 1 \
  freq 500.000000 \
];
# kernel clock 'PL 0' (0)
set dict_kernel_clk_clk [dict create \
  is_user_set false \
  clk_id 0 \
  freq 300.000000 \
];

set kernel_clock_freqs [dict create \
  kernel2_clk_clk $dict_kernel2_clk_clk \
  kernel_clk_clk $dict_kernel_clk_clk \
];

set dict_clk_main_a0 [dict create \
  is_user_set false \
  clk_id "" \
  freq_orig 250 \
  freq 250 \
];
set system_clock_freqs [dict create \
  clk_main_a0 $dict_clk_main_a0 \
];

set clk_info [dict create \
  kernel_clock_freqs         $kernel_clock_freqs \
  system_clock_freqs         $system_clock_freqs \
  worst_negative_slack      0 \
  max_frequency             500 \
  min_frequency             60 \
  error_on_hold_violation   true \
  skip_timing_and_scaling   false \
  enable_auto_freq_scale    true \
];

set dict_debug [dict create \
  version "1.0" \
];
dict set dict_debug kernel_debug true
set dict_profile [dict create \
  NAME profile_monitors \
  FIFO "8192" \
  DATA [list] \
  STALL [list] \
  EXEC [list] \
];
set debug_profile_info [dict create debug $dict_debug profile $dict_profile]

source [dict get $config_info scripts_dir]/_vivado_params.tcl


OPTRACE "END" "ipirun" ""

